// frontend/storefront/src/components/front/Cart.tsx
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Spinner } from "@/components/ui/spinner";
import { CartItemResponse } from "@/interfaces/cart.interface";
import { useCartStore, useUserStore } from "@/stores";
import { formatCurrency } from "@/utils/formatter.util";
import { Minus, Plus, X } from "lucide-react";
import Image from "next/image";
import { useRouter } from "next/navigation";
import React, { useEffect, useState } from "react";
import { toast } from "sonner";

const Cart: React.FC = () => {
  const [isCheckingOut, setIsCheckingOut] = useState(false);
  const {
    cart,
    loadCart,
    getCartTotal,
    getItemTotal,
    removeFromCart,
    updateQuantity,
    isLoading,
    error,
  } = useCartStore();
  const { isAuthenticated } = useUserStore();
  const router = useRouter();

  const total = getCartTotal();

  // Load cart data on component mount
  useEffect(() => {
    const loadData = async () => {
      if (!isAuthenticated()) return;

      // Only load cart if we don't have it yet and not currently loading
      if (!cart && !isLoading) {
        try {
          await loadCart();
        } catch (error) {
          console.error('Failed to load cart data:', error);
          toast.error('Failed to load cart data');
        }
      }
    };

    loadData();
  }, [isAuthenticated, cart, isLoading, loadCart]);

  const handleRemoveFromCart = async (productId: number) => {
    const success = await removeFromCart(productId);
    if (success) {
      toast.success('Item removed from cart');
    } else {
      toast.error('Failed to remove item from cart');
    }
  };

  const handleIncreaseQuantity = async (item: CartItemResponse) => {
    const success = await updateQuantity(item.product.id, item.quantity + 1);
    if (!success) {
      toast.error('Failed to update quantity');
    }
  };

  const handleDecreaseQuantity = async (item: CartItemResponse) => {
    const success = await updateQuantity(item.product.id, item.quantity - 1);
    if (!success) {
      toast.error('Failed to update quantity');
    }
  };

  const handleCheckout = async () => {
    if (!cart?.cartItems.length || isCheckingOut) {
      return;
    }

    if (!isAuthenticated()) {
      router.push("/login");
      return;
    }

    try {
      setIsCheckingOut(true);
      
      // Redirect to checkout page
      router.push("/checkout");
    } catch (error) {
      console.error("Checkout failed:", error);
      toast.error("Failed to proceed to checkout. Please try again.");
    } finally {
      setIsCheckingOut(false);
    }
  };

  return (
    <Card className="shopping-cart shadow-sm">
      <CardHeader>
        <CardTitle className="text-center">Your Cart</CardTitle>
      </CardHeader>
      <CardContent>
        {isLoading ? (
          <div className="text-center py-8">
            <Spinner className="text-blue-600 mx-auto" />
            <p className="mt-2 text-gray-500">Loading cart...</p>
          </div>
        ) : error ? (
          <div className="text-center py-8">
            <p className="text-red-500">Error loading cart: {error}</p>
            <Button 
              onClick={() => window.location.reload()} 
              variant="outline" 
              className="mt-2"
            >
              Retry
            </Button>
          </div>
        ) : cart?.cartItems && cart.cartItems.length > 0 ? (
          <div className="space-y-3 mb-6">
            {cart.cartItems.map((item: CartItemResponse) => (
              <div
                key={item.product.id}
                className="border-b border-gray-200 last:border-b-0 py-3"
              >
                <div className="flex items-center gap-3">
                  {/* Remove button */}
                  <Button
                    onClick={() => handleRemoveFromCart(item.product.id)}
                    variant="ghost"
                    size="sm"
                    className="text-red-500 hover:text-red-700 p-1 h-auto"
                    disabled={isCheckingOut || isLoading}
                  >
                    <X className="h-4 w-4" />
                  </Button>

                  {/* Product image */}
                  <Image
                    src={item.product.image || "/placeholder-image.jpg"}
                    alt={item.product.name}
                    className="cart-item-image"
                    width={60}
                    height={60}
                    style={{
                      objectFit: "cover",
                      borderRadius: "4px",
                    }}
                  />

                  {/* Product name */}
                  <div className="flex-1">
                    <span className="font-semibold">{item.product.name}</span>
                  </div>

                  {/* Quantity controls */}
                  <div className="flex items-center gap-2">
                    <Button
                      onClick={() => handleDecreaseQuantity(item)}
                      variant="outline"
                      size="sm"
                      className="h-8 w-8 p-0"
                      disabled={isCheckingOut || isLoading}
                    >
                      <Minus className="h-3 w-3" />
                    </Button>
                    <Input
                      type="number"
                      value={item.quantity}
                      onChange={async (e: React.ChangeEvent<HTMLInputElement>) => {
                        const newQuantity = parseInt(e.target.value) || 1;
                        if (newQuantity !== item.quantity) {
                          const success = await updateQuantity(item.product.id, newQuantity);
                          if (!success) {
                            toast.error('Failed to update quantity');
                          }
                        }
                      }}
                      className="w-12 h-8 text-center text-sm"
                      min="1"
                      disabled={isCheckingOut || isLoading}
                    />
                    <Button
                      onClick={() => handleIncreaseQuantity(item)}
                      variant="outline"
                      size="sm"
                      className="h-8 w-8 p-0"
                      disabled={isCheckingOut || isLoading}
                    >
                      <Plus className="h-3 w-3" />
                    </Button>
                  </div>

                  {/* Price */}
                  <span className="font-bold">
                    {formatCurrency(getItemTotal(item.product.id))}
                  </span>
                </div>
              </div>
            ))}
          </div>
        ) : (
          <p className="text-center text-gray-500 py-8">Your cart is empty.</p>
        )}

        {cart?.cartItems && cart.cartItems.length > 0 && (
          <>
            <div className="flex justify-between items-center pt-4 border-t border-gray-200">
              <span className="font-bold text-lg">Total:</span>
              <span className="font-bold text-lg">{formatCurrency(total)}</span>
            </div>

            <Button
              onClick={handleCheckout}
              className="w-full mt-6"
              disabled={!cart?.cartItems.length || isCheckingOut || isLoading}
            >
              {isCheckingOut ? "Redirecting..." : "Proceed to Checkout"}
            </Button>
          </>
        )}
      </CardContent>
    </Card>
  );
};

export default Cart;

// frontend-bk/src/components/front/Cart.vue
<template>
  <div class="shopping-cart p-4 border bg-light shadow-sm rounded">
    <h5 class="mb-4 text-center">Your Cart</h5>

    <ul v-if="cart.length" class="list-group mb-3">
      <li
        v-for="item in cart"
        :key="item.product.id"
        class="list-group-item border-0 border-bottom py-3"
      >
        <div class="d-flex align-items-center gap-3">
          <!-- Remove button -->
          <button
            @click="removeFromCart(item.product.id)"
            class="btn btn-link text-danger p-0 fs-5"
            :disabled="isProcessing"
          >
            <i class="bi bi-x"></i>
          </button>

          <!-- Product image -->
          <img
            :src="getProductImageUrl(item.product.image)"
            :alt="item.product.name"
            class="cart-item-image"
          />

          <!-- Product name -->
          <div class="flex-grow-1">
            <strong>{{ item.product.name }}</strong>
          </div>

          <!-- Quantity controls -->
          <div class="d-flex align-items-center gap-2">
            <button
              @click="decreaseQuantity(item)"
              class="btn btn-sm btn-outline-secondary"
              :disabled="isProcessing"
            >
              -
            </button>
            <input
              type="number"
              v-model.number="item.quantity"
              class="form-control form-control-sm text-center"
              style="width: 40px"
              min="1"
              @change="updateQuantity(item.product.id, item.quantity)"
              :disabled="isProcessing"
            />
            <button
              @click="increaseQuantity(item)"
              class="btn btn-sm btn-outline-secondary"
              :disabled="isProcessing"
            >
              +
            </button>
          </div>

          <!-- Price -->
          <span class="fw-bold">${{ formatCurrency(cartStore.getItemTotal(item)) }}</span>
        </div>
      </li>
    </ul>

    <p v-else class="text-center text-muted">Your cart is empty.</p>

    <div v-if="cart.length" class="d-flex justify-content-between mt-3">
      <span class="fw-bold">Total:</span>
      <span class="fw-bold">${{ formatCurrency(total) }}</span>
    </div>

    <button
      @click="handlePlaceOrder"
      class="btn btn-success w-100 mt-4"
      :disabled="!cart.length || isProcessing"
    >
      {{ isProcessing ? "Processing..." : "Place Order" }}
    </button>
  </div>
</template>

<script setup lang="ts">
import type { PlaceOrderItemRequest } from '@/interfaces/order.interface';
import { orderService } from '@/services';
import { useCartStore, type CartItem } from '@/stores/cart.store';
import { useUserStore } from '@/stores/user.store';
import { formatCurrency } from '@/utils/formatter.util';
import { getProductImageUrl } from '@/utils/productImage.util';
import { computed, ref } from 'vue';
import { useRouter } from 'vue-router';

const isProcessing = ref(false);
const cartStore = useCartStore();
const userStore = useUserStore();
const router = useRouter();

const cart = computed(() => cartStore.cart);
const total = computed(() => cartStore.getTotal());

function removeFromCart(productId: number) {
  cartStore.removeFromCart(productId);
}

function increaseQuantity(item: CartItem) {
  cartStore.updateQuantity(item.product.id, item.quantity + 1);
}

function decreaseQuantity(item: CartItem) {
  if (item.quantity <= 1) {
    cartStore.removeFromCart(item.product.id);
  } else {
    cartStore.updateQuantity(item.product.id, item.quantity - 1);
  }
}

function updateQuantity(productId: number, quantity: number) {
  cartStore.updateQuantity(productId, quantity > 0 ? quantity : 1);
}

async function handlePlaceOrder() {
  if (!cart.value.length || isProcessing.value) return;

  if (!userStore.isAuthenticated) {
    router.push({ name: 'login' });
    return
  }

  try {
    isProcessing.value = true;

    const orderItems = cart.value.map((cartItem) => ({
      productId: cartItem.product.id,
      quantity: cartItem.quantity,
    } as PlaceOrderItemRequest));

    const response = await orderService.placeOrder({orderItems});
    
    if (response.success && response.data) {
      cartStore.currentOrderId = response.data;
      cartStore.clearCart();
    } else {
      console.error('Failed to place order:', response.errorMessage);
    }
  } catch (err: any) {
    console.error('Failed to place order:', err?.message || err);
  } finally {
    isProcessing.value = false;
  }
}
</script>

<style scoped>
.shopping-cart {
  background-color: #f8f9fa;
  border-radius: 5px;
}

.cart-item-image {
  width: 60px;
  height: 60px;
  object-fit: cover;
  border-radius: 4px;
}

input[type='number']::-webkit-inner-spin-button,
input[type='number']::-webkit-outer-spin-button {
  -webkit-appearance: none;
  margin: 0;
}
</style>
