// frontend/src/app/cart/page.tsx
"use client";

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { CartItemResponse } from "@/interfaces/cart.interface";
import { useCartStore } from "@/stores/cart.store";
import { useUserStore } from "@/stores/user.store";
import { formatCurrency } from "@/utils/formatter.util";
import { ArrowLeft, CreditCard, Minus, Plus, ShoppingCart, Trash2 } from "lucide-react";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";

export default function CartPage() {
  const router = useRouter();
  const { isAuthenticated, isAdmin } = useUserStore();
  const { cart, loadCart, updateQuantity, removeFromCart, clearCart, isLoading, getCartTotal } = useCartStore();
  
  const [updating, setUpdating] = useState(false);
  const [checkingOut, setCheckingOut] = useState(false);

  // Redirect if not authenticated or is admin
  useEffect(() => {
    if (!isAuthenticated() || isAdmin()) {
      router.push("/");
      return;
    }
  }, [isAuthenticated, isAdmin, router]);

  // Load cart data
  // Load cart data on component mount
  useEffect(() => {
    if (isAuthenticated() && !isAdmin()) {
      loadCart();
    }
  }, [isAuthenticated, isAdmin, loadCart]);



  const handleUpdateQuantity = async (productId: number, newQuantity: number) => {
    try {
      setUpdating(true);
      await updateQuantity(productId, newQuantity);
    } catch (error) {
      console.error("Failed to update quantity:", error);
    } finally {
      setUpdating(false);
    }
  };

  const handleRemoveItem = async (productId: number) => {
    try {
      setUpdating(true);
      await removeFromCart(productId);
    } catch (error) {
      console.error("Failed to remove item:", error);
    } finally {
      setUpdating(false);
    }
  };

  const handleClearCart = async () => {
    try {
      setUpdating(true);
      await clearCart();
    } catch (error) {
      console.error("Failed to clear cart:", error);
    } finally {
      setUpdating(false);
    }
  };

  const handleCheckout = async () => {
    try {
      setCheckingOut(true);
      
      // Redirect to checkout page
      router.push("/checkout");
    } catch (error) {
      console.error("Checkout failed:", error);
      alert("Checkout failed. Please try again.");
    } finally {
      setCheckingOut(false);
    }
  };

  if (isLoading) {
    return (
      <div className="container mx-auto px-4 py-8 pt-20">
        <div className="flex items-center justify-center min-h-[400px]">
          <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-primary"></div>
        </div>
      </div>
    );
  }

  const cartItems = cart?.cartItems || [];
  const totalAmount = getCartTotal();
  const isEmpty = cartItems.length === 0;

  return (
    <div className="min-h-screen bg-gray-50 py-8">
      <div className="max-w-4xl mx-auto px-4">
        {/* Header */}
        <div className="flex items-center gap-3 mb-8">
          <div className="p-2 bg-primary/10 rounded-lg">
            <ShoppingCart className="h-6 w-6 text-primary" />
          </div>
          <h1 className="text-2xl font-bold text-gray-900">
            Shopping Cart
          </h1>
        </div>

        {isEmpty ? (
          <Card className="shadow-sm border-0 bg-white">
            <CardContent className="flex flex-col items-center justify-center py-8">
              <h2 className="text-xl font-semibold text-gray-800 mb-4">
                Your cart is empty
              </h2>
              <Button onClick={() => router.push("/")} size="lg" className="px-8">
                <ArrowLeft className="h-4 w-4" />
                Continue Shopping
              </Button>
            </CardContent>
          </Card>
        ) : (
          <div className="space-y-6">
            {/* Cart Items */}
            <Card className="shadow-sm border-0 bg-white">
              <CardHeader className="flex flex-row items-center justify-between pb-4">
                <CardTitle className="text-lg font-semibold text-gray-900">
                  Items ({cartItems.length})
                </CardTitle>
                <Button
                  variant="outline"
                  size="sm"
                  onClick={handleClearCart}
                  disabled={updating}
                  className="text-red-600 hover:text-red-700 border-red-200 hover:bg-red-50"
                >
                  <Trash2 className="h-4 w-4 mr-2" />
                  Clear all
                </Button>
              </CardHeader>
              <CardContent className="space-y-3 pt-0">
                {cartItems.map((item: CartItemResponse) => (
                  <div key={item.product.id} className="flex items-center gap-4 p-4 bg-gray-50 rounded-xl border border-gray-100 hover:shadow-sm transition-shadow">
                    <div className="flex-1 min-w-0">
                      <h3 className="font-semibold text-gray-900 truncate">{item.product.name}</h3>
                      <div className="flex items-center gap-2 mt-2">
                        <Badge variant="secondary" className="bg-blue-100 text-blue-800 hover:bg-blue-100">
                          {formatCurrency(item.product.price)}
                        </Badge>
                        {item.product.categories && item.product.categories.length > 0 && (
                          <Badge variant="outline" className="border-gray-300 text-gray-600">
                            {item.product.categories[0].name}
                          </Badge>
                        )}
                      </div>
                    </div>
                    
                    <div className="flex items-center gap-1 bg-white rounded-lg border border-gray-200 p-1">
                      <Button
                        variant="ghost"
                        size="sm"
                        onClick={() => handleUpdateQuantity(item.product.id, item.quantity - 1)}
                        disabled={updating || item.quantity <= 1}
                        className="h-8 w-8 p-0 hover:bg-gray-100"
                      >
                        <Minus className="h-3 w-3" />
                      </Button>
                      <span className="w-10 text-center font-semibold text-sm">
                        {item.quantity}
                      </span>
                      <Button
                        variant="ghost"
                        size="sm"
                        onClick={() => handleUpdateQuantity(item.product.id, item.quantity + 1)}
                        disabled={updating}
                        className="h-8 w-8 p-0 hover:bg-gray-100"
                      >
                        <Plus className="h-3 w-3" />
                      </Button>
                    </div>
                    
                    <div className="flex items-center gap-3">
                      <p className="font-bold text-lg text-gray-900 min-w-0">
                        {formatCurrency(item.product.price * item.quantity)}
                      </p>
                      <Button
                        variant="ghost"
                        size="sm"
                        onClick={() => handleRemoveItem(item.product.id)}
                        disabled={updating}
                        className="text-red-600 hover:text-red-700 hover:bg-red-50 h-8 w-8 p-0"
                      >
                        <Trash2 className="h-4 w-4" />
                      </Button>
                    </div>
                  </div>
                ))}
              </CardContent>
            </Card>

             {/* Total and Checkout */}
             <Card className="shadow-sm border-0 bg-white sticky bottom-4">
               <CardContent className="p-6">
                 <div className="flex items-center justify-between mb-6">
                   <span className="text-xl font-semibold text-gray-700">Total:</span>
                   <span className="text-xl font-bold text-gray-900">{formatCurrency(totalAmount)}</span>
                 </div>
                 <div className="space-y-3">
                   <Button
                     onClick={handleCheckout}
                     disabled={checkingOut}
                     className="w-full bg-gradient-to-r from-blue-600 to-blue-700 hover:from-blue-700 hover:to-blue-800 text-white shadow-lg hover:shadow-xl transition-all duration-200"
                     size="lg"
                   >
                     {checkingOut ? (
                       <div className="flex items-center gap-2">
                         <div className="animate-spin rounded-full h-5 w-5 border-b-2 border-white"></div>
                         Processing...
                       </div>
                     ) : (
                       <>
                         <CreditCard className="h-5 w-5 mr-2" />
                         Proceed to Checkout
                       </>
                     )}
                   </Button>
                   <Button
                     onClick={() => router.push("/")}
                     variant="outline"
                     className="w-full border-gray-300 text-gray-700 hover:bg-gray-50 hover:text-gray-900 transition-all duration-200"
                     size="lg"
                   >
                     <ShoppingCart className="h-5 w-5 mr-2" />
                     Continue Shopping
                   </Button>
                 </div>
               </CardContent>
             </Card>
          </div>
        )}
      </div>
    </div>
  );
}

// frontend-bk/src/components/front/Cart.vue
<template>
  <div class="shopping-cart p-4 border bg-light shadow-sm rounded">
    <h5 class="mb-4 text-center">Your Cart</h5>

    <ul v-if="cart.length" class="list-group mb-3">
      <li
        v-for="item in cart"
        :key="item.product.id"
        class="list-group-item border-0 border-bottom py-3"
      >
        <div class="d-flex align-items-center gap-3">
          <!-- Remove button -->
          <button
            @click="removeFromCart(item.product.id)"
            class="btn btn-link text-danger p-0 fs-5"
            :disabled="isProcessing"
          >
            <i class="bi bi-x"></i>
          </button>

          <!-- Product image -->
          <img
            :src="getProductImageUrl(item.product.image)"
            :alt="item.product.name"
            class="cart-item-image"
          />

          <!-- Product name -->
          <div class="flex-grow-1">
            <strong>{{ item.product.name }}</strong>
          </div>

          <!-- Quantity controls -->
          <div class="d-flex align-items-center gap-2">
            <button
              @click="decreaseQuantity(item)"
              class="btn btn-sm btn-outline-secondary"
              :disabled="isProcessing"
            >
              -
            </button>
            <input
              type="number"
              v-model.number="item.quantity"
              class="form-control form-control-sm text-center"
              style="width: 40px"
              min="1"
              @change="updateQuantity(item.product.id, item.quantity)"
              :disabled="isProcessing"
            />
            <button
              @click="increaseQuantity(item)"
              class="btn btn-sm btn-outline-secondary"
              :disabled="isProcessing"
            >
              +
            </button>
          </div>

          <!-- Price -->
          <span class="fw-bold">${{ formatCurrency(cartStore.getItemTotal(item)) }}</span>
        </div>
      </li>
    </ul>

    <p v-else class="text-center text-muted">Your cart is empty.</p>

    <div v-if="cart.length" class="d-flex justify-content-between mt-3">
      <span class="fw-bold">Total:</span>
      <span class="fw-bold">${{ formatCurrency(total) }}</span>
    </div>

    <button
      @click="handlePlaceOrder"
      class="btn btn-success w-100 mt-4"
      :disabled="!cart.length || isProcessing"
    >
      {{ isProcessing ? "Processing..." : "Place Order" }}
    </button>
  </div>
</template>

<script setup lang="ts">
import type { PlaceOrderItemRequest } from '@/interfaces/order.interface';
import { orderService } from '@/services';
import { useCartStore, type CartItem } from '@/stores/cart.store';
import { useUserStore } from '@/stores/user.store';
import { formatCurrency } from '@/utils/formatter.util';
import { getProductImageUrl } from '@/utils/productImage.util';
import { computed, ref } from 'vue';
import { useRouter } from 'vue-router';

const isProcessing = ref(false);
const cartStore = useCartStore();
const userStore = useUserStore();
const router = useRouter();

const cart = computed(() => cartStore.cart);
const total = computed(() => cartStore.getTotal());

function removeFromCart(productId: number) {
  cartStore.removeFromCart(productId);
}

function increaseQuantity(item: CartItem) {
  cartStore.updateQuantity(item.product.id, item.quantity + 1);
}

function decreaseQuantity(item: CartItem) {
  if (item.quantity <= 1) {
    cartStore.removeFromCart(item.product.id);
  } else {
    cartStore.updateQuantity(item.product.id, item.quantity - 1);
  }
}

function updateQuantity(productId: number, quantity: number) {
  cartStore.updateQuantity(productId, quantity > 0 ? quantity : 1);
}

async function handlePlaceOrder() {
  if (!cart.value.length || isProcessing.value) return;

  if (!userStore.isAuthenticated) {
    router.push({ name: 'login' });
    return
  }

  try {
    isProcessing.value = true;

    const orderItems = cart.value.map((cartItem) => ({
      productId: cartItem.product.id,
      quantity: cartItem.quantity,
    } as PlaceOrderItemRequest));

    const response = await orderService.placeOrder({orderItems});
    
    if (response.success && response.data) {
      cartStore.currentOrderId = response.data;
      cartStore.clearCart();
    } else {
      console.error('Failed to place order:', response.errorMessage);
    }
  } catch (err: any) {
    console.error('Failed to place order:', err?.message || err);
  } finally {
    isProcessing.value = false;
  }
}
</script>

<style scoped>
.shopping-cart {
  background-color: #f8f9fa;
  border-radius: 5px;
}

.cart-item-image {
  width: 60px;
  height: 60px;
  object-fit: cover;
  border-radius: 4px;
}

input[type='number']::-webkit-inner-spin-button,
input[type='number']::-webkit-outer-spin-button {
  -webkit-appearance: none;
  margin: 0;
}
</style>
