// frontend/storefront/src/components/product/ProductSearch.tsx
import { Metadata } from "@/api/apiClient";
import { catalogApi } from "@/api/index.api";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import {
  Pagination,
  PaginationContent,
  PaginationItem,
  PaginationLink,
  PaginationNext,
  PaginationPrevious,
} from "@/components/ui/pagination";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Spinner } from "@/components/ui/spinner";
import { Brand, Category, Product } from "@/interfaces";
import { useCartStore, useUserStore } from "@/stores";

import { RotateCcw, Search } from "lucide-react";
import { useRouter, useSearchParams } from "next/navigation";
import React, { useCallback, useEffect, useRef, useState } from "react";
import { toast } from "sonner";
import ProductCard from "./ProductCard";
import ProductDetailsModal from "./ProductDetailsModal";

// Types for better type safety
interface SearchFilters {
  keyword?: string;
  minPrice?: number;
  maxPrice?: number;
  brandId?: string;
  categoryIds?: number[];
  mode?: "DATABASE" | "FULL_TEXT_SEARCH";
}

const ProductSearch: React.FC = () => {
  const { addToCart } = useCartStore();
  const { isAuthenticated } = useUserStore();
  const router = useRouter();
  const searchParams = useSearchParams();
  const isInitialized = useRef(false);
  const lastRefreshParam = useRef<string | null>(null);

  const [isModalOpen, setIsModalOpen] = useState(false);
  const [selectedProduct, setSelectedProduct] = useState<Product | null>(null);
  const [isLoadingProductDetails, setIsLoadingProductDetails] = useState(false);

  // Brands state
  const [brands, setBrands] = useState<Brand[]>([]);
  const [isLoadingBrands, setIsLoadingBrands] = useState(true);

  // Categories state
  const [categories, setCategories] = useState<Category[]>([]);
  const [isLoadingCategories, setIsLoadingCategories] = useState(true);

  // Products state
  const [products, setProducts] = useState<Product[]>([]);
  const [isLoadingProducts, setIsLoadingProducts] = useState(false);
  const [pagination, setPagination] = useState<Metadata>({
    currentPage: 1,
    totalPages: 1,
    totalRecords: 0,
    pageSize: 20,
  });

  // Filter state - current form values being edited by user
  const [formFilters, setFormFilters] = useState<SearchFilters>({
    keyword: "",
    minPrice: undefined,
    maxPrice: undefined,
    brandId: "",
    categoryIds: [],
    mode: "DATABASE",
  });

  // Filter update functions
  const updateFilter = useCallback(
    <K extends keyof SearchFilters>(key: K, value: SearchFilters[K]) => {
      setFormFilters((prev) => ({ ...prev, [key]: value }));
    },
    []
  );

  const resetFilters = useCallback(() => {
    setFormFilters({
      keyword: "",
      minPrice: undefined,
      maxPrice: undefined,
      brandId: "",
      categoryIds: [],
      mode: "DATABASE",
    });
  }, []);

  const updateNumericFilter = useCallback(
    (key: "minPrice" | "maxPrice", value: string) => {
      const numValue = value ? parseFloat(value) : undefined;
      updateFilter(key, numValue);
    },
    [updateFilter]
  );

  const changeCategory = useCallback((categoryId: number) => {
    setFormFilters((prev) => ({
      ...prev,
      categoryIds: prev.categoryIds?.includes(categoryId)
        ? prev.categoryIds.filter((id) => id !== categoryId)
        : [...(prev.categoryIds ?? []), categoryId],
    }));
  }, []);

  // Committed search filters
  const [committedSearchFilters, setCommittedSearchFilters] =
    useState<SearchFilters>({});

  // Load brands data
  const loadBrands = useCallback(async () => {
    try {
      setIsLoadingBrands(true);

      const brandsResponse = await catalogApi.retrieveAllBrand();

      if (!brandsResponse.success) {
        throw new Error(brandsResponse.errorMessage || "Failed to load brands");
      }

      setBrands(brandsResponse.data || []);
    } catch (error) {
      const errorMessage =
        error instanceof Error ? error.message : "Failed to load brands";
      toast.error(errorMessage);
    } finally {
      setIsLoadingBrands(false);
    }
  }, []);

  // Load categories data
  const loadCategories = useCallback(async () => {
    try {
      setIsLoadingCategories(true);

      const categoriesResponse = await catalogApi.retrieveAllCategory();

      if (!categoriesResponse.success) {
        throw new Error(
          categoriesResponse.errorMessage || "Failed to load categories"
        );
      }

      setCategories(categoriesResponse.data || []);
    } catch (error) {
      const errorMessage =
        error instanceof Error ? error.message : "Failed to load categories";
      toast.error(errorMessage);
    } finally {
      setIsLoadingCategories(false);
    }
  }, []);

  // Load products data
  const loadProducts = useCallback(
    async (
      filters: SearchFilters = {},
      page: number = 1,
      pageSize: number = 20
    ) => {
      try {
        setIsLoadingProducts(true);

        // Clean up filters for API call
        const apiSearchParams = {
          page,
          size: pageSize,
          keyword: filters.keyword || undefined,
          minPrice: filters.minPrice,
          maxPrice: filters.maxPrice,
          brandId: filters.brandId || undefined,
          categoryIds: filters.categoryIds?.length
            ? filters.categoryIds
            : undefined,
          mode: filters.mode || "DATABASE",
        };

        const response = await catalogApi.retrieveProductList(apiSearchParams);

        if (!response.success) {
          throw new Error(response.errorMessage || "Failed to load products");
        }

        setProducts(response.data || []);
        setPagination({
          currentPage: page,
          totalPages: response.metadata?.totalPages || 1,
          totalRecords: response.metadata?.totalRecords || 0,
          pageSize: response.metadata?.pageSize || 20,
        });
      } catch (error) {
        const errorMessage =
          error instanceof Error ? error.message : "Failed to load products";
        toast.error(errorMessage);
        setProducts([]);
      } finally {
        setIsLoadingProducts(false);
      }
    },
    []
  );

  // Go to specific page
  const goToPage = useCallback(
    (page: number) => {
      loadProducts(committedSearchFilters, page, pagination.pageSize);
    },
    [loadProducts, committedSearchFilters, pagination.pageSize]
  );

  const changePage = (newPage: number) => {
    if (newPage >= 1 && newPage <= pagination.totalPages) {
      goToPage(newPage);
    }
  };

  // Load product details
  const loadProductDetails = useCallback(async (productId: number) => {
    try {
      setIsLoadingProductDetails(true);
      const response = await catalogApi.retrieveProduct(productId);
      
      if (!response.success) {
        throw new Error(response.errorMessage || "Failed to load product details");
      }
      
      setSelectedProduct(response.data);
    } catch (error) {
      const errorMessage =
        error instanceof Error ? error.message : "Failed to load product details";
      toast.error(errorMessage);
      setSelectedProduct(null);
    } finally {
      setIsLoadingProductDetails(false);
    }
  }, []);

  // Simplified event handlers
  const handleAddToCart = useCallback(
    async (product: Product) => {
      // Check if user is authenticated
      if (!isAuthenticated()) {
        toast.info("Please login to add items to cart");
        router.push("/login");
        return;
      }

      try {
        const success = await addToCart(product.id, 1);
        
        if (success) {
          toast.success(`${product.name} added to cart`);
        } else {
          toast.error("Failed to add product to cart");
        }
      } catch (error) {
        toast.error("Failed to add product to cart");
        console.error(error);
      }
    },
    [addToCart, isAuthenticated, router]
  );

  const handleProductClick = useCallback((product: Product) => {
    setIsModalOpen(true);
    setSelectedProduct(null); // Clear previous product
    loadProductDetails(product.id); // Load full details
  }, [loadProductDetails]);

  const handleCloseModal = useCallback(() => {
    setIsModalOpen(false);
    setSelectedProduct(null);
  }, []);

  // Initial data loading - load static data once and initial products
  useEffect(() => {
    const refreshParam = searchParams.get("refresh");

    // This effect should run only once on initialization or when a new refresh is triggered
    if (isInitialized.current && !refreshParam) {
      return;
    }

    // If it's a refresh, ensure it's a new one
    if (refreshParam && refreshParam === lastRefreshParam.current) {
      return;
    }

    if (refreshParam) {
      lastRefreshParam.current = refreshParam;
    }

    const initializeData = async () => {
      // Reset filters if it's a refresh
      if (refreshParam) {
        setFormFilters({
          keyword: "",
          minPrice: undefined,
          maxPrice: undefined,
          brandId: "",
          categoryIds: [],
          mode: "DATABASE",
        });
        setCommittedSearchFilters({});
      }

      // Fetch all data
      await Promise.all([
        loadBrands(),
        loadCategories(),
        loadProducts(refreshParam ? {} : committedSearchFilters, 1, 9),
      ]);
    };

    initializeData();

    // Mark as initialized after the first load
    if (!isInitialized.current) {
      isInitialized.current = true;
    }
  }, [
    searchParams,
    loadBrands,
    loadCategories,
    loadProducts,
    committedSearchFilters,
  ]);

  // Loading states
  const isLoading = isLoadingBrands || isLoadingCategories || isLoadingProducts;

  const handleSearch = useCallback(() => {
    // Commit form filters to search and trigger search
    setCommittedSearchFilters(formFilters);
    // Only load products, not static data
    loadProducts(formFilters, 1, pagination.pageSize);
  }, [formFilters, loadProducts, pagination.pageSize]
  );

  return (
    <div className="grid grid-cols-12 gap-6">
      {/* Filters Column - Left Side (col-4) */}
      <div className="col-span-12 lg:col-span-4">
        <Card className="sticky top-4">
          <CardHeader>
            <CardTitle>Search Filters</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="space-y-6">
                {/* Search Input */}
                <div>
                  <label
                    htmlFor="keyword"
                    className="block text-sm font-medium text-gray-700 mb-2"
                  >
                    Product Keyword
                  </label>
                  <input
                    id="keyword"
                    type="text"
                    className="w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                    placeholder="Product name, description, attributes, etc."
                    value={formFilters.keyword || ""}
                    onChange={(e) => updateFilter("keyword", e.target.value)}
                  />
                </div>

                {/* Price Range */}
                 <div>
                   <label className="block text-sm font-medium text-gray-700 mb-2">
                     Price Range
                   </label>
                   <div className="grid grid-cols-2 gap-3">
                     <div>
                       <input
                         type="number"
                         className="w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                         placeholder="Min Price"
                         min="0"
                         step="0.01"
                         value={formFilters.minPrice || ""}
                         onChange={(e) =>
                           updateNumericFilter("minPrice", e.target.value)
                         }
                       />
                     </div>
                     <div>
                       <input
                         type="number"
                         className="w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                         placeholder="Max Price"
                         min="0"
                         step="0.01"
                         value={formFilters.maxPrice || ""}
                         onChange={(e) =>
                           updateNumericFilter("maxPrice", e.target.value)
                         }
                       />
                     </div>
                   </div>
                 </div>

                {/* Brand Filter */}
                <div>
                  <label
                    htmlFor="brand"
                    className="block text-sm font-medium text-gray-700 mb-2"
                  >
                    Brand
                  </label>
                  {isLoadingBrands ? (
                    <div className="flex justify-center py-3">
                      <Spinner className="text-blue-600" />
                    </div>
                  ) : (
                    <>
                      <Select
                        disabled={!brands.length}
                        value={formFilters.brandId || "all"}
                        onValueChange={(value) =>
                          updateFilter(
                            "brandId",
                            value === "all" ? "" : value
                          )
                        }
                      >
                        <SelectTrigger>
                          <SelectValue placeholder="All Brands" />
                        </SelectTrigger>
                        <SelectContent>
                          <SelectItem value="all">All Brands</SelectItem>
                          {brands.map((brand) => (
                            <SelectItem
                              key={brand.id}
                              value={brand.id.toString()}
                            >
                              {brand.name}
                            </SelectItem>
                          ))}
                        </SelectContent>
                      </Select>
                      {!brands.length && (
                        <div className="text-gray-500 text-sm mt-1">
                          No brands available
                        </div>
                      )}
                    </>
                  )}
                </div>

                {/* Category Filter */}
                <div>
                  <label
                    htmlFor="category"
                    className="block text-sm font-medium text-gray-700 mb-2"
                  >
                    Categories
                  </label>
                  {isLoadingCategories ? (
                    <div className="flex justify-center py-3">
                      <Spinner className="text-blue-600" />
                    </div>
                  ) : (
                    <>
                      <Select value="placeholder" onValueChange={() => {}}>
                        <SelectTrigger>
                          <SelectValue>
                            {formFilters.categoryIds &&
                            formFilters.categoryIds.length > 0
                              ? `${formFilters.categoryIds.length} categories selected`
                              : "All Categories"}
                          </SelectValue>
                        </SelectTrigger>
                        <SelectContent>
                          {categories.map((category) => (
                            <label
                              key={category.id}
                              className="flex items-center space-x-2 cursor-pointer hover:bg-gray-50 p-1 rounded"
                            >
                              <input
                                type="checkbox"
                                className="rounded border-gray-300 text-blue-600 focus:ring-blue-500"
                                checked={
                                  formFilters.categoryIds?.includes(
                                    category.id
                                  ) ?? false
                                }
                                onChange={() => changeCategory(category.id)}
                              />
                              <span className="text-sm">{category.name}</span>
                            </label>
                          ))}
                        </SelectContent>
                      </Select>
                      {!categories.length && (
                        <div className="text-gray-500 text-sm mt-1">
                          No categories available
                        </div>
                      )}
                    </>
                  )}
                </div>

                {/* Search Mode */}
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    Search Mode
                  </label>
                  <div className="space-y-2">
                    <label className="flex items-center space-x-2 cursor-pointer">
                      <input
                        type="radio"
                        name="searchMode"
                        value="DATABASE"
                        checked={formFilters.mode === "DATABASE"}
                        onChange={(e) => updateFilter("mode", e.target.value as "DATABASE" | "FULL_TEXT_SEARCH")}
                        className="w-4 h-4 text-blue-600 border-gray-300 focus:ring-blue-500"
                      />
                      <span className="text-sm">Database Search</span>
                    </label>
                    <label className="flex items-center space-x-2 cursor-pointer">
                      <input
                        type="radio"
                        name="searchMode"
                        value="FULL_TEXT_SEARCH"
                        checked={formFilters.mode === "FULL_TEXT_SEARCH"}
                        onChange={(e) => updateFilter("mode", e.target.value as "DATABASE" | "FULL_TEXT_SEARCH")}
                        className="w-4 h-4 text-blue-600 border-gray-300 focus:ring-blue-500"
                      />
                      <span className="text-sm">Full Text Search</span>
                    </label>
                  </div>
                </div>

                {/* Action Buttons */}
                 <div className="flex gap-3">
                   <Button
                     type="button"
                     variant="default"
                     onClick={handleSearch}
                     disabled={isLoading}
                   >
                     <Search className="w-4 h-4" />
                     Search
                   </Button>
                   <Button
                     type="button"
                     variant="outline"
                     onClick={resetFilters}
                     disabled={isLoading}
                   >
                     <RotateCcw className="w-4 h-4" />
                     Reset
                   </Button>
                 </div>
              </div>
          </CardContent>
        </Card>
      </div>

      {/* Products Column - Right Side (col-8) */}
      <div className="col-span-12 lg:col-span-8">
        {/* Search Results Card */}
        <Card className="mb-6">
          <CardHeader>
            <CardTitle>Search Results</CardTitle>
          </CardHeader>
          <CardContent>
            {isLoadingProducts ? (
              <div className="flex justify-center py-12">
                <Spinner className="text-blue-600" />
              </div>
            ) : products.length > 0 ? (
              <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-6">
                {products.map((product) => (
                  <ProductCard
                    key={product.id}
                    product={product}
                    onProductClick={handleProductClick}
                    onAddToCart={handleAddToCart}
                  />
                ))}
              </div>
            ) : (
              <p className="text-center text-gray-500 py-8">No products found.</p>
            )}
          </CardContent>
        </Card>

        {/* Pagination */}
        {pagination.totalPages > 1 && (
          <div className="flex justify-center">
            <Pagination>
              <PaginationContent>
                <PaginationItem>
                  <PaginationPrevious
                    onClick={() => changePage(pagination.currentPage - 1)}
                    className={
                      pagination.currentPage === 1
                        ? "pointer-events-none opacity-50"
                        : "cursor-pointer"
                    }
                  />
                </PaginationItem>

                {Array.from(
                  { length: pagination.totalPages },
                  (_, i) => i + 1
                ).map((page) => (
                  <PaginationItem key={page}>
                    <PaginationLink
                      onClick={() => changePage(page)}
                      isActive={pagination.currentPage === page}
                      className="cursor-pointer"
                    >
                      {page}
                    </PaginationLink>
                  </PaginationItem>
                ))}

                <PaginationItem>
                  <PaginationNext
                    onClick={() => changePage(pagination.currentPage + 1)}
                    className={
                      pagination.currentPage === pagination.totalPages
                        ? "pointer-events-none opacity-50"
                        : "cursor-pointer"
                    }
                  />
                </PaginationItem>
              </PaginationContent>
            </Pagination>
          </div>
        )}
      </div>

      {/* Product Details Modal */}
      <ProductDetailsModal
        isOpen={isModalOpen}
        product={selectedProduct}
        isLoading={isLoadingProductDetails}
        onClose={handleCloseModal}
      />
    </div>
  );
};

export default ProductSearch;

// frontend-bk/src/components/front/ProductSearch.vue
<template>
  <div class="search-product p-4 border bg-light shadow-sm rounded mb-3">
    <!-- Filters Form -->
    <form @submit.prevent="applyFilters(1)" class="bg-white p-4 rounded-3 mb-4 border">
      <div class="row g-3">
        <!-- Search Input -->
        <div class="col-md-12">
          <label for="keyword" class="form-label">Search Products</label>
          <input
            id="keyword"
            v-model.trim="filters.keyword"
            type="text"
            class="form-control"
            placeholder="Search products..."
          />
        </div>

        <!-- Price Range -->
        <div class="col-md-12">
          <label class="form-label">Price Range</label>
          <div class="row g-3">
            <div class="col-md-6">
              <input
                v-model.number="filters.minPrice"
                type="number"
                class="form-control"
                placeholder="Min Price"
                min="0"
                step="0.01"
              />
            </div>
            <div class="col-md-6">
              <input
                v-model.number="filters.maxPrice"
                type="number"
                class="form-control"
                placeholder="Max Price"
                min="0"
                step="0.01"
              />
            </div>
          </div>
        </div>

        <!-- Brand and Category Filters -->
        <div class="col-md-12">
          <div class="row g-3">
            <div class="col-md-6">
              <label for="brandId" class="form-label">Brand</label>
              <div v-if="isLoadingBrands" class="text-center py-2" aria-live="polite">
                <div class="spinner-border spinner-border-sm" role="status" aria-label="Loading brands">
                  <span class="visually-hidden">Loading...</span>
                </div>
              </div>
              <select
                v-else
                id="brandId"
                v-model="filters.brandId"
                class="form-select"
                :disabled="!brands.length"
              >
                <option value="">All Brands</option>
                <option v-for="brand in brands" :key="brand.id" :value="brand.id">
                  {{ brand.name }}
                </option>
              </select>
              <div v-if="!brands.length && !isLoadingBrands" class="text-muted small mt-1">
                No brands available
              </div>
            </div>
            <div class="col-md-6">
              <label for="categoryIds" class="form-label">Categories</label>
              <div v-if="isLoadingCategories" class="text-center py-2" aria-live="polite">
                <div class="spinner-border spinner-border-sm" role="status" aria-label="Loading categories">
                  <span class="visually-hidden">Loading...</span>
                </div>
              </div>
              <select
                v-else
                id="categoryIds"
                v-model="filters.categoryIds"
                class="form-select"
                multiple
                :disabled="!categories.length"
                size="3"
              >
                <option v-for="category in categories" :key="category.id" :value="category.id">
                  {{ category.name }}
                </option>
              </select>
              <div v-if="!categories.length && !isLoadingCategories" class="text-muted small mt-1">
                No categories available
              </div>
              <small v-if="!isLoadingCategories" class="text-muted">Hold Ctrl/Cmd to select multiple</small>
            </div>
          </div>
        </div>

        <!-- Submit Button -->
        <div class="col-md-12 mt-3">
          <button type="submit" class="btn btn-primary">
            <i class="bi bi-search"></i> Search
          </button>
          <button type="button" @click="resetFilters" class="btn btn-outline-secondary ms-2">
            <i class="bi bi-arrow-counterclockwise"></i> Reset
          </button>
        </div>
      </div>
    </form>

    <!-- Products Grid -->
    <div v-if="isLoadingProducts" class="text-center py-5" aria-live="polite">
      <div class="spinner-border" role="status" aria-label="Loading products">
        <span class="visually-hidden">Loading...</span>
      </div>
    </div>
    <div v-else-if="products && products.length" class="mt-4 row g-3">
      <div v-for="product in products" :key="product.id" class="col-md-4">
        <div class="card h-100 shadow-sm">
          <img
            :src="getProductImageUrl(product.image)"
            class="card-img-top product-image"
            :alt="product.name"
          />
          <div class="card-body d-flex flex-column">
            <h5 class="card-title product-name" @click="showProductDetails(product)">
              {{ product.name }}
            </h5>
            <h6 class="card-subtitle mb-3 text-muted">
              ${{ formatCurrency(product.price) }}
            </h6>
            <button @click="handleAddToCart(product)" class="btn btn-primary mt-auto">
              Add to Cart
            </button>
          </div>
        </div>
      </div>
    </div>
    <p v-else class="text-center text-muted mt-3">No products found.</p>

    <!-- Product Details Modal -->
    <ProductDetailsModal v-model="showModal" :product="selectedProduct" :is-loading="isLoadingProduct" />

    <!-- Pagination -->
    <div v-if="metadata.totalPages > 1" class="d-flex justify-content-center align-items-center mt-4 gap-3">
      <button
        class="btn btn-outline-secondary"
        @click="changePage(metadata.currentPage - 1)"
        :disabled="metadata.currentPage === 1"
      >
        Previous
      </button>
      <span>Page {{ metadata.currentPage }} of {{ metadata.totalPages }}</span>
      <button
        class="btn btn-outline-secondary"
        @click="changePage(metadata.currentPage + 1)"
        :disabled="metadata.currentPage === metadata.totalPages"
      >
        Next
      </button>
    </div>
  </div>
</template>

<script setup lang="ts">
import type { Brand, Category, Product, SearchProductFilters } from '@/interfaces/product.interface';
import { productService } from '@/services';
import { useCartStore } from '@/stores/cart.store';
import { formatCurrency } from '@/utils/formatter.util';
import { getProductImageUrl } from '@/utils/productImage.util';
import { onMounted, reactive, ref } from 'vue';
import { toast } from 'vue3-toastify';
import ProductDetailsModal from './ProductDetailsModal.vue';

const cartStore = useCartStore();

const showModal = ref(false);
const products = ref<Product[]>([]);
const categories = ref<Category[]>([]);
const brands = ref<Brand[]>([]);
const selectedProduct = ref<Product | null>(null);
const isLoadingProducts = ref(false);
const isLoadingProduct = ref(false);
const isLoadingBrands = ref(false);
const isLoadingCategories = ref(false);

const metadata = reactive({
  currentPage: 1,
  pageSize: 9,
  totalPages: 1,
  totalRecords: 0,
});

const filters = reactive<SearchProductFilters>({
  keyword: undefined,
  minPrice: undefined,
  maxPrice: undefined,
  brandId: '',
  categoryIds: [],
  page: 1,
  size: 9,
});

const loadBrands = async () => {
  isLoadingBrands.value = true;
  try {
    const { data } = await productService.listBrand();
    brands.value = data;
  } catch {
    toast.error('Failed to load brands');
  } finally {
    isLoadingBrands.value = false;
  }
};

const loadCategories = async () => {
  isLoadingCategories.value = true;
  try {
    const { data } = await productService.listCategory();
    categories.value = data;
  } catch {
    toast.error('Failed to load categories');
  } finally {
    isLoadingCategories.value = false;
  }
};

const applyFilters = async (page: number) => {
  if (isLoadingProducts.value) return;

  isLoadingProducts.value = true;
  try {
    filters.page = page;
    metadata.currentPage = page;
    const response = await productService.searchProduct(filters);
    products.value = response.data;
    Object.assign(metadata, {
      currentPage: response.metadata?.currentPage ?? 1,
      pageSize: response.metadata?.pageSize ?? 9,
      totalPages: response.metadata?.totalPages ?? 1,
      totalRecords: response.metadata?.totalRecords ?? 0,
    });
  } catch {
    toast.error('Failed to load products');
  } finally {
    isLoadingProducts.value = false;
  }
};

const changePage = (newPage: number) => {
  if (newPage >= 1 && newPage <= metadata.totalPages) {
    applyFilters(newPage);
  }
};

const resetFilters = () => {
  Object.assign(filters, {
    keyword: undefined,
    minPrice: undefined,
    maxPrice: undefined,
    brandId: undefined,
    categoryIds: undefined,
    page: 1,
    size: 9,
  });
  applyFilters(1);
};

const showProductDetails = async (product: Product) => {
  isLoadingProduct.value = true; // Set loading state
  try {
    const response = await productService.getProduct(product.id); // Fetch product details
    selectedProduct.value = response.data; // Set fetched product
    showModal.value = true; // Open modal
  } catch (error) {
    toast.error('Failed to load product details');
    console.error(error);
  } finally {
    isLoadingProduct.value = false; // Reset loading state
  }
};

const handleAddToCart = (product: Product) => {
  cartStore.addToCart(product);
};

onMounted(async () => {
  await Promise.all([loadBrands(), loadCategories(), applyFilters(1)]);
});
</script>

<style scoped>
.product-image {
  height: 180px;
  object-fit: cover;
}

.product-name {
  cursor: pointer;
  transition: color 0.2s;
}

.product-name:hover {
  color: #0d6efd;
  text-decoration: underline;
}
</style>
