// frontend/src/components/front/ProductDetailsModal.tsx
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Table, TableBody, TableCell, TableRow } from "@/components/ui/table";
import { Product } from "@/interfaces";
import { useCartStore } from "@/stores";
import { getProductImageUrl } from "@/utils/productImage.util";
import { Loader2 } from "lucide-react";
import Image from "next/image";
import React from "react";
import { toast } from "sonner";

interface ProductDetailsModalProps {
  isOpen: boolean;
  product?: Product | null;
  isLoading?: boolean;
  onClose: () => void;
}

const ProductDetailsModal: React.FC<ProductDetailsModalProps> = ({
  isOpen,
  product,
  isLoading = false,
  onClose,
}) => {
  const { addToCart } = useCartStore();

  const handleAddToCart = () => {
    if (product) {
      try {
        addToCart({
          productId: product.id,
          name: product.name,
          price: product.price,
          imageUrl: getProductImageUrl(product.image),
        });
        toast.success(`${product.name} added to cart`);
        onClose();
      } catch (error) {
        toast.error("Failed to add product to cart");
        console.error(error);
      }
    }
  };

  return (
    <Dialog open={isOpen} onOpenChange={onClose}>
      <DialogContent className="max-w-4xl max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle>Product Details</DialogTitle>
        </DialogHeader>
        <div className="mt-4">
          {isLoading ? (
            <div className="flex justify-center py-8">
              <Loader2 className="h-8 w-8 animate-spin" />
            </div>
          ) : product ? (
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div>
                <Image
                  src={getProductImageUrl(product.image)}
                  className="w-full h-96 object-cover object-center rounded-lg"
                  alt={product.name}
                  width={400}
                  height={384}
                />
              </div>
              <div className="space-y-4">
                <h3 className="text-2xl font-bold">{product.name}</h3>
                <p className="text-3xl font-semibold text-primary">
                  ${product.price.toFixed(2)}
                </p>

                <div>
                  <h4 className="text-lg font-semibold mb-2">Description</h4>
                  <p className="text-muted-foreground">
                    {product.details?.description ||
                      "No description available."}
                  </p>
                </div>

                {product.attributes && product.attributes.length > 0 ? (
                  <div>
                    <h4 className="text-lg font-semibold mb-2">Attributes</h4>
                    <Table>
                      <TableBody>
                        {product.attributes.map((attribute) => (
                          <TableRow key={attribute.id}>
                            <TableCell className="font-medium text-muted-foreground">
                              {attribute.name}
                            </TableCell>
                            <TableCell>{attribute.value}</TableCell>
                          </TableRow>
                        ))}
                      </TableBody>
                    </Table>
                  </div>
                ) : (
                  <p className="text-muted-foreground">
                    No attributes available.
                  </p>
                )}

                <div>
                  <h4 className="text-lg font-semibold mb-2">Brand</h4>
                  <p className="text-muted-foreground">
                    {product.brand?.name || "N/A"}
                  </p>
                </div>

                <div>
                  <h4 className="text-lg font-semibold mb-2">Categories</h4>
                  {product.categories && product.categories.length > 0 ? (
                    <div className="flex flex-wrap gap-2">
                      {product.categories.map((category) => (
                        <Badge key={category.id} variant="secondary">
                          {category.name}
                        </Badge>
                      ))}
                    </div>
                  ) : (
                    <p className="text-muted-foreground">N/A</p>
                  )}
                </div>

                <Button onClick={handleAddToCart} className="w-full" size="lg">
                  Add to Cart
                </Button>
              </div>
            </div>
          ) : (
            <div className="text-center text-muted-foreground py-8">
              No product details available.
            </div>
          )}
        </div>
      </DialogContent>
    </Dialog>
  );
};

export default ProductDetailsModal;

// frontend-bk/src/components/front/ProductDetailsModal.vue
<template>
  <div v-if="modelValue" class="modal-backdrop show" @click="closeModal"></div>
  <div v-if="modelValue" class="modal show d-block" tabindex="-1">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Product Details</h5>
          <button type="button" class="btn-close" @click="closeModal"></button>
        </div>
        <div class="modal-body">
          <div v-if="isLoading" class="text-center py-5">
            <div class="spinner-border text-primary" role="status">
              <span class="visually-hidden">Loading...</span>
            </div>
          </div>
          <div v-else-if="product" class="row">
            <div class="col-md-6">
              <img :src="getProductImageUrl(product.image)" class="img-fluid rounded product-detail-image"
                :alt="product.name" />
            </div>
            <div class="col-md-6">
              <h4 class="mb-3">{{ product.name }}</h4>
              <h5 class="text-primary mb-4">${{ product.price.toFixed(2) }}</h5>

              <div class="mb-3">
                <h6>Description</h6>
                <p class="text-muted">{{ product.details.description || 'No description available.' }}</p>
              </div>

              <div v-if="product.attributes?.length" class="mb-1">
                <h6>Attributes</h6>
                <div class="table-responsive">
                  <table class="table table-bordered table-sm">
                    <tbody>
                      <tr v-for="attribute in product.attributes" :key="attribute.id">
                        <th class="text-muted">{{ attribute.name }}</th>
                        <td>{{ attribute.value }}</td>
                      </tr>
                    </tbody>
                  </table>
                </div>
              </div>
              <p v-else class="text-muted">No attributes available.</p>

              <div class="mb-4">
                <h6>Brand</h6>
                <p>{{ product.brand?.name || 'N/A' }}</p>
              </div>

              <div class="mb-4">
                <h6>Categories</h6>
                <div v-if="product.categories?.length" class="d-flex flex-wrap gap-2">
                  <span v-for="category in product.categories" :key="category.id" class="badge bg-secondary">
                    {{ category.name }}
                  </span>
                </div>
                <p v-else class="text-muted">N/A</p>
              </div>

              <div class="d-grid">
                <button @click="handleAddToCart" class="btn btn-primary">
                  Add to Cart
                </button>
              </div>
            </div>
          </div>
          <div v-else class="text-center text-muted py-5">
            No product details available.
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { useCartStore } from '@/stores/cart.store'
import { defineEmits, defineProps, withDefaults } from 'vue'
import { toast } from 'vue3-toastify'
import type { Product } from '../../interfaces/product.interface'
import { getProductImageUrl } from '../../utils/productImage.util'

// Initialize cart store
const cartStore = useCartStore()

// Define props with TypeScript
const props = withDefaults(defineProps<{
  modelValue: boolean
  product?: Product | null
  isLoading?: boolean
}>(), {
  product: null,
  isLoading: false
})

// Define emits
const emit = defineEmits<{
  (e: 'update:modelValue', value: boolean): void
}>()

const closeModal = () => {
  emit('update:modelValue', false)
}

const handleAddToCart = () => {
  if (props.product) {
    try {
      cartStore.addToCart(props.product)
      toast.success(`${props.product.name} added to cart`)
      closeModal()
    } catch (error) {
      toast.error('Failed to add product to cart')
      console.error(error)
    }
  }
}
</script>

<style scoped>
.product-detail-image {
  width: 100%;
  height: 400px;
  object-fit: cover;
  object-position: center;
}

.modal-backdrop {
  opacity: 0.5;
}
</style>
