// frontend/admin/src/components/admin/ImportDropdown.tsx
"use client";

import React, { useState } from "react";
import { Button } from "@/components/ui/button";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import {
  Upload,
  FileText,
  FileSpreadsheet,
  Loader2,
  ChevronDown,
} from "lucide-react";

interface ImportDropdownProps {
  isImporting?: boolean;
  variant?:
    | "primary"
    | "secondary"
    | "success"
    | "danger"
    | "warning"
    | "info"
    | "light"
    | "dark";
  outline?: boolean;
  onImport: (fileType: "csv" | "excel") => void;
  onOpen?: () => void;
  onClose?: () => void;
}

const ImportDropdown: React.FC<ImportDropdownProps> = ({
  isImporting = false,
  variant = "primary",
  outline = true,
  onImport,
  onOpen,
  onClose,
}) => {
  const [isOpen, setIsOpen] = useState(false);

  const getVariant = () => {
    if (outline) {
      return "outline";
    }
    switch (variant) {
      case "danger":
        return "destructive";
      case "secondary":
        return "secondary";
      default:
        return "default";
    }
  };

  const handleImport = (fileType: "csv" | "excel") => {
    onImport(fileType);
  };

  const handleOpenChange = (open: boolean) => {
    setIsOpen(open);
    if (open) {
      onOpen?.();
    } else {
      onClose?.();
    }
  };

  return (
    <DropdownMenu open={isOpen} onOpenChange={handleOpenChange}>
      <DropdownMenuTrigger asChild>
        <Button variant={getVariant()} disabled={isImporting} className="gap-2">
          {isImporting ? (
            <>
              <Loader2 className="h-4 w-4 animate-spin" />
              Importing...
            </>
          ) : (
            <>
              <Upload className="h-4 w-4" />
              Import
              <ChevronDown className="h-4 w-4" />
            </>
          )}
        </Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent>
        <DropdownMenuItem
          onClick={() => handleImport("csv")}
          disabled={isImporting}
          className="gap-2"
        >
          <FileText className="h-4 w-4" />
          Import from CSV
        </DropdownMenuItem>
        <DropdownMenuItem
          onClick={() => handleImport("excel")}
          disabled={isImporting}
          className="gap-2"
        >
          <FileSpreadsheet className="h-4 w-4" />
          Import from Excel
        </DropdownMenuItem>
      </DropdownMenuContent>
    </DropdownMenu>
  );
};

export default ImportDropdown;

// frontend-bk/src/components/admin/ImportDropdown.vue
<template>
  <Dropdown
    :button-class="buttonClass"
    :disabled="isImporting"
    @open="$emit('open')"
    @close="$emit('close')"
  >
    <template #button>
      <i class="bi bi-upload me-1"></i>
      <span v-if="isImporting">
        <span class="spinner-border spinner-border-sm me-1" role="status" aria-hidden="true"></span>
        Importing...
      </span>
      <span v-else>Import</span>
    </template>
    
    <template #menu="{ close }">
      <li>
        <button 
          class="dropdown-item" 
          type="button"
          @click="handleImport('csv', close)" 
          :disabled="isImporting"
        >
          <i class="bi bi-filetype-csv me-2"></i>Import from CSV
        </button>
      </li>
      <li>
        <button 
          class="dropdown-item" 
          type="button"
          @click="handleImport('xlsx', close)" 
          :disabled="isImporting"
        >
          <i class="bi bi-filetype-xlsx me-2"></i>Import from Excel
        </button>
      </li>
    </template>
  </Dropdown>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import Dropdown from '../common/Dropdown.vue';

interface Props {
  isImporting?: boolean;
  variant?: 'primary' | 'secondary' | 'success' | 'danger' | 'warning' | 'info' | 'light' | 'dark';
  outline?: boolean;
}

const props = withDefaults(defineProps<Props>(), {
  isImporting: false,
  variant: 'primary',
  outline: true
});

const emit = defineEmits<{
  import: [fileType: 'csv' | 'xlsx']
  open: []
  close: []
}>();

const buttonClass = computed(() => {
  const baseClass = 'btn dropdown-toggle';
  const variantClass = props.outline ? `btn-outline-${props.variant}` : `btn-${props.variant}`;
  return `${baseClass} ${variantClass}`;
});

const handleImport = (fileType: 'csv' | 'xlsx', closeDropdown: () => void) => {
  closeDropdown();
  emit('import', fileType);
};
</script>
