// frontend/storefront/src/app/login/page.tsx
"use client";

import { Alert, AlertDescription } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from "@/components/ui/form";
import { Input } from "@/components/ui/input";
import { LoginRequest } from "@/interfaces";
import { zodResolver } from "@hookform/resolvers/zod";
import { Eye, EyeOff, Loader2, Lock, User } from "lucide-react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import React, { useState } from "react";
import { useForm } from "react-hook-form";
import { toast } from "sonner";
import { z } from "zod";
import { withGuestOnly } from "../../hoc/withAuth";
import { useUserStore } from "../../stores/user.store";

const formSchema = z.object({
  username: z.string().min(1, {
    message: "Username is required.",
  }),
  password: z
    .string()
    .min(1, { message: "Password is required." }),
});

const Login: React.FC = () => {
  const [errorMessage, setErrorMessage] = useState("");
  const [isLoggingIn, setIsLoggingIn] = useState(false);
  const [isPasswordVisible, setIsPasswordVisible] = useState(false);
  const { login } = useUserStore();
  const router = useRouter();

  // Get redirect parameter from URL
  const getRedirectUrl = () => {
    if (typeof window !== "undefined") {
      const urlParams = new URLSearchParams(window.location.search);
      return urlParams.get("redirect") || null;
    }
    return null;
  };

  const form = useForm<z.infer<typeof formSchema>>({
    resolver: zodResolver(formSchema),
    defaultValues: {
      username: "",
      password: "",
    },
  });

  const onSubmit = async (values: z.infer<typeof formSchema>) => {
    try {
      setIsLoggingIn(true);
      setErrorMessage("");

      const credentials: LoginRequest = {
        username: values.username,
        password: values.password,
      };

      const response = await login(credentials);

      if (response.success) {
        toast.success("Login successful!");

        // Add a small delay to ensure tokens are properly set before redirect
        await new Promise((resolve) => setTimeout(resolve, 100));

        // Check if there's a redirect URL from the middleware
        const redirectUrl = getRedirectUrl();

        if (redirectUrl) {
          // Use the redirect URL from middleware
          console.log("Redirecting to original destination:", redirectUrl);
          router.push(redirectUrl);
        } else {
          console.log("No redirect URL, letting useGuestRedirect handle redirect");
        }
      } else {
        const message = response.errorMessage || "Login failed. Please check your credentials.";
        setErrorMessage(message);
      }
    } catch {
      const message = "An unexpected error occurred. Please try again.";
      setErrorMessage(message);
    } finally {
      setIsLoggingIn(false);
    }
  };

  return (
    <div className="h-screen flex items-start justify-center pt-40">
      <Card className="w-full max-w-md">
        <CardHeader className="text-center space-y-2 pb-4">
          <div>
            <CardTitle className="text-2xl font-bold text-primary">
              Welcome Back
            </CardTitle>
            <p className="text-muted-foreground mt-2">
              Sign in to your account
            </p>
          </div>
        </CardHeader>

        <CardContent className="space-y-6">
          {errorMessage && (
            <Alert variant="destructive">
              <AlertDescription>{errorMessage}</AlertDescription>
            </Alert>
          )}

          <Form {...form}>
            <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-4">
              <FormField
                control={form.control}
                name="username"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Username</FormLabel>
                    <FormControl>
                      <div className="relative">
                        <User className="absolute left-3 top-1/2 transform -translate-y-1/2 h-4 w-4 text-muted-foreground" />
                        <Input
                          {...field}
                          type="text"
                          className={`pl-10 ${errorMessage ? "border-red-500 focus-visible:ring-red-500" : ""}`}
                          placeholder="Enter your username"
                        />
                      </div>
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />

              <FormField
                control={form.control}
                name="password"
                render={({ field }) => (
                  <FormItem>
                    <div className="flex justify-between items-center">
                      <FormLabel>Password</FormLabel>
                    </div>
                    <FormControl>
                      <div className="relative">
                        <Lock className="absolute left-3 top-1/2 transform -translate-y-1/2 h-4 w-4 text-muted-foreground" />
                        <Input
                          {...field}
                          type={isPasswordVisible ? "text" : "password"}
                          className={`pl-10 pr-10 ${errorMessage ? "border-red-500 focus-visible:ring-red-500" : ""}`}
                          placeholder="Enter your password"
                        />
                        <Button
                          type="button"
                          variant="ghost"
                          size="icon-xs"
                          className="absolute right-2 top-1/2 -translate-y-1/2 text-muted-foreground hover:text-foreground"
                          aria-label={
                            isPasswordVisible ? "Hide password" : "Show password"
                          }
                          onClick={() =>
                            setIsPasswordVisible((current) => !current)
                          }
                        >
                          {isPasswordVisible ? (
                            <EyeOff className="size-4" />
                          ) : (
                            <Eye className="size-4" />
                          )}
                        </Button>
                      </div>
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />

              <Button
                type="submit"
                className="w-full"
                size="lg"
                disabled={isLoggingIn}
              >
                {isLoggingIn ? (
                  <>
                    <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                    Signing In...
                  </>
                ) : (
                  "Sign In"
                )}
              </Button>

              <div className="text-center">
                <p className="text-sm text-muted-foreground">
                  Don&apos;t have an account?{" "}
                  <Link
                    href="/register"
                    className="text-primary hover:underline font-medium"
                  >
                    Sign up
                  </Link>
                </p>
              </div>
            </form>
          </Form>
        </CardContent>
      </Card>
    </div>
  );
};

export default withGuestOnly(Login);

// frontend/src/pages/auth/Login.vue
<template>
  <div class="login-container d-flex align-items-center justify-content-center min-vh-100">
    <div class="login-card bg-white p-4 p-md-5 rounded-4 shadow-lg">
      <div class="text-center mb-4">
        <img src="@/assets/images/logo.svg" alt="Atlas Logo" class="logo mb-3" />
        <h3 class="fw-bold text-primary">Welcome Back</h3>
        <p class="text-muted">Sign in to your account</p>
      </div>
      
      <div v-if="successMessage" class="alert alert-success" role="alert">
        {{ successMessage }}
      </div>
      <div v-if="errorMessage" class="alert alert-danger" role="alert">
        {{ errorMessage }}
      </div>
      
      <form @submit.prevent="handleLogin">
        <div class="mb-4">
          <label class="form-label fw-medium">Username</label>
          <div class="position-relative">
            <i class="bi bi-person position-absolute top-50 start-0 translate-middle-y ms-3 text-muted"></i>
            <input v-model="username" type="text" class="form-control form-control-lg ps-5" placeholder="Enter your username" required />
          </div>
        </div>
        
        <div class="mb-4">
          <div class="d-flex justify-content-between">
            <label class="form-label fw-medium">Password</label>
            <a href="#" class="text-decoration-none small">Forgot password?</a>
          </div>
          <div class="position-relative">
            <i class="bi bi-lock position-absolute top-50 start-0 translate-middle-y ms-3 text-muted"></i>
            <input v-model="password" type="password" class="form-control form-control-lg ps-5" placeholder="Enter your password" required />
          </div>
        </div>
        
        <button type="submit" class="btn btn-primary btn-lg w-100 mb-4">
          <span v-if="isLoggingIn" class="spinner-border spinner-border-sm me-2" role="status" aria-hidden="true"></span>
          <span v-else><i class="bi bi-box-arrow-in-right me-2"></i></span>
          Sign In
        </button>
        
        <div class="text-center">
          <p class="text-muted">Don't have an account? <router-link to="/register" class="text-decoration-none fw-medium">Sign up</router-link></p>
        </div>
      </form>
    </div>
  </div>
</template>

<script setup lang="ts">
import type { LoginRequest } from '@/interfaces/auth.interface'
import { useUserStore } from '@/stores/user.store'
import { ref } from 'vue'
import { useRouter } from 'vue-router'

const username = ref('')
const password = ref('')
const successMessage = ref('')
const errorMessage = ref('')
const isLoggingIn = ref(false)
const userStore = useUserStore()
const router = useRouter()

const handleLogin = async () => {
  try {
    isLoggingIn.value = true
    errorMessage.value = ''
    
    const credentials: LoginRequest = {
      identifier: username.value,
      password: password.value
    }
    
    const response = await userStore.login(credentials)
    if (response.success) {
      router.push('/')
    } else {
      errorMessage.value = response.errorMessage || 'Login failed. Please check your credentials.'
    }
  } catch (error) {
    errorMessage.value = 'An unexpected error occurred. Please try again.'
  } finally {
    isLoggingIn.value = false
  }
}
</script>

<style scoped>
.login-container {
  background: linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%);
}

.login-card {
  width: 100%;
  max-width: 450px;
  transition: all 0.3s ease;
}

.logo {
  height: 60px;
  width: auto;
}

.form-control:focus {
  border-color: #4dabf7;
  box-shadow: 0 0 0 0.25rem rgba(77, 171, 247, 0.25);
}

.btn-primary {
  background-color: #41b883;
  border-color: #41b883;
  transition: all 0.2s;
}

.btn-primary:hover, .btn-primary:focus {
  background-color: #34a873;
  border-color: #34a873;
  transform: translateY(-2px);
  box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
}

.btn-primary:active {
  transform: translateY(0);
}

@media (max-width: 576px) {
  .login-card {
    margin: 1rem;
  }
}
</style>
