// frontend/src/pages/auth/Register.vue
<template>
  <div class="register-container d-flex align-items-center justify-content-center min-vh-100">
    <div class="register-card bg-white p-4 p-md-5 rounded-4 shadow-lg">
      <div class="text-center mb-4">
        <img src="@/assets/images/logo.svg" alt="Atlas Logo" class="logo mb-3" />
        <h3 class="fw-bold text-primary">Create Account</h3>
        <p class="text-muted">Join our community today</p>
      </div>
      
      <div v-if="successMessage" class="alert alert-success" role="alert">
        {{ successMessage }}
      </div>
      <div v-if="errorMessage" class="alert alert-danger" role="alert">
        {{ errorMessage }}
      </div>
      
      <form @submit.prevent="submit">
        <div class="row g-3">
          <div class="col-md-6 mb-3">
            <label class="form-label fw-medium">First Name</label>
            <div class="position-relative">
              <i class="bi bi-person position-absolute top-50 start-0 translate-middle-y ms-3 text-muted"></i>
              <input v-model="firstName" type="text" class="form-control ps-5" placeholder="First name" required />
            </div>
          </div>
          
          <div class="col-md-6 mb-3">
            <label class="form-label fw-medium">Last Name</label>
            <div class="position-relative">
              <i class="bi bi-person position-absolute top-50 start-0 translate-middle-y ms-3 text-muted"></i>
              <input v-model="lastName" type="text" class="form-control ps-5" placeholder="Last name" required />
            </div>
          </div>
          
          <div class="col-12 mb-3">
            <label class="form-label fw-medium">Username</label>
            <div class="position-relative">
              <i class="bi bi-person-badge position-absolute top-50 start-0 translate-middle-y ms-3 text-muted"></i>
              <input v-model="username" type="text" class="form-control ps-5" placeholder="Choose a username" required />
            </div>
          </div>
          
          <div class="col-12 mb-3">
            <label class="form-label fw-medium">Email</label>
            <div class="position-relative">
              <i class="bi bi-envelope position-absolute top-50 start-0 translate-middle-y ms-3 text-muted"></i>
              <input v-model="email" type="email" class="form-control ps-5" placeholder="Your email address" required />
            </div>
          </div>
          
          <div class="col-12 mb-3">
            <label class="form-label fw-medium">Phone Number</label>
            <div class="position-relative">
              <i class="bi bi-phone position-absolute top-50 start-0 translate-middle-y ms-3 text-muted"></i>
              <input v-model="phoneNumber" type="text" class="form-control ps-5" placeholder="Your phone number" required />
            </div>
          </div>
          
          <div class="col-md-6 mb-3">
            <label class="form-label fw-medium">Password</label>
            <div class="position-relative">
              <i class="bi bi-lock position-absolute top-50 start-0 translate-middle-y ms-3 text-muted"></i>
              <input v-model="password" type="password" class="form-control ps-5" placeholder="Create password" required />
            </div>
          </div>
          
          <div class="col-md-6 mb-3">
            <label class="form-label fw-medium">Confirm Password</label>
            <div class="position-relative">
              <i class="bi bi-lock-fill position-absolute top-50 start-0 translate-middle-y ms-3 text-muted"></i>
              <input v-model="confirmPassword" type="password" class="form-control ps-5" placeholder="Confirm password" required />
            </div>
          </div>
          
          <div class="col-12 mt-2">
            <button type="submit" class="btn btn-primary btn-lg w-100 mb-3">
              <i class="bi bi-person-plus me-2"></i>Register
            </button>
            
            <div class="text-center">
              <p class="text-muted">Already have an account? <router-link to="/login" class="text-decoration-none fw-medium">Sign in</router-link></p>
            </div>
          </div>
        </div>
      </form>
    </div>
  </div>
</template>

<script setup lang="ts">
import type { RegisterRequest } from '@/interfaces/user.interface';
import { userService } from '@/services';
import { ref } from 'vue';
import { useRouter } from 'vue-router';

const router = useRouter();

// Form state
const username = ref<string>('');
const firstName = ref<string>('');
const lastName = ref<string>('');
const email = ref<string>('');
const phoneNumber = ref<string>('');
const password = ref<string>('');
const confirmPassword = ref<string>('');
const successMessage = ref<string>('');
const errorMessage = ref<string>('');

// API call to register
const submit = async () => {
  errorMessage.value = '';
  
  if (password.value !== confirmPassword.value) {
    errorMessage.value = 'Passwords do not match';
    return;
  }

  const request: RegisterRequest = {
    username: username.value,
    firstName: firstName.value,
    lastName: lastName.value,
    email: email.value,
    phoneNumber: phoneNumber.value,
    password: password.value,
  };

  try {
    await userService.register(request);
    successMessage.value = 'You registered successfully';
    resetForm();
    setTimeout(goToLogin, 1000);
  } catch (error) {
    errorMessage.value = 'Registration request failed: ' + error;
  }
};

const goToLogin = () => {
  router.push({ name: 'login' });
};

// Reset form fields
const resetForm = () => {
  username.value = '';
  firstName.value = '';
  lastName.value = '';
  email.value = '';
  phoneNumber.value = '';
  password.value = '';
  confirmPassword.value = '';
};  
</script>

<style scoped>
.register-container {
  background: linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%);
}

.register-card {
  width: 100%;
  max-width: 700px;
  transition: all 0.3s ease;
}

.logo {
  height: 60px;
  width: auto;
}

.form-control:focus {
  border-color: #4dabf7;
  box-shadow: 0 0 0 0.25rem rgba(77, 171, 247, 0.25);
}

.btn-primary {
  background-color: #41b883;
  border-color: #41b883;
  transition: all 0.2s;
}

.btn-primary:hover, .btn-primary:focus {
  background-color: #34a873;
  border-color: #34a873;
  transform: translateY(-2px);
  box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
}

.btn-primary:active {
  transform: translateY(0);
}

@media (max-width: 576px) {
  .register-card {
    margin: 1rem;
  }
}
</style>

// frontend/storefront/src/app/register/page.tsx
"use client";

import { identityApi } from "@/api/index.api";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from "@/components/ui/form";
import { Input } from "@/components/ui/input";
import { withGuestOnly } from "@/hoc/withAuth";
import { RegisterRequest } from "@/interfaces";
import { zodResolver } from "@hookform/resolvers/zod";
import { Loader2, Lock, Mail, Phone, User, UserPlus } from "lucide-react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import React, { useState } from "react";
import { useForm } from "react-hook-form";
import { toast } from "sonner";
import { z } from "zod";

const formSchema = z
  .object({
    username: z.string().min(2, {
      message: "Username must be at least 2 characters.",
    }),
    firstName: z.string().min(1, {
      message: "First name is required.",
    }),
    lastName: z.string().min(1, {
      message: "Last name is required.",
    }),
    email: z.string().email({
      message: "Please enter a valid email address.",
    }),
    phoneNumber: z.string().min(1, {
      message: "Phone number is required.",
    }),
    password: z.string().min(6, {
      message: "Password must be at least 6 characters.",
    }),
    confirmPassword: z.string().min(6, {
      message: "Password must be at least 6 characters.",
    }),
  })
  .refine((data) => data.password === data.confirmPassword, {
    message: "Passwords don't match",
    path: ["confirmPassword"],
  });

const Register: React.FC = () => {
  const [errorMessage, setErrorMessage] = useState("");
  const [isRegistering, setIsRegistering] = useState(false);
  const router = useRouter();

  const form = useForm<z.infer<typeof formSchema>>({
    resolver: zodResolver(formSchema),
    defaultValues: {
      username: "",
      firstName: "",
      lastName: "",
      email: "",
      phoneNumber: "",
      password: "",
      confirmPassword: "",
    },
  });

  const goToLogin = () => {
    router.push("/login");
  };

  const onSubmit = async (values: z.infer<typeof formSchema>) => {
    setErrorMessage("");

    const request: RegisterRequest = {
      username: values.username,
      firstName: values.firstName,
      lastName: values.lastName,
      email: values.email,
      phoneNumber: values.phoneNumber,
      password: values.password,
    };

    try {
      setIsRegistering(true);
      await identityApi.register(request);
      toast.success("Registration successful!");
      form.reset();
      setTimeout(goToLogin, 1000);
    } catch (error) {
      setErrorMessage("Registration request failed: " + error);
    } finally {
      setIsRegistering(false);
    }
  };

  return (
    <div className="h-screen flex items-start justify-center pt-20">
      <Card className="w-full max-w-2xl">
        <CardHeader className="text-center space-y-2 pb-4">
          <div>
            <CardTitle className="text-2xl font-bold text-primary">
              Create Account
            </CardTitle>
            <p className="text-muted-foreground mt-2">
              Join our community today
            </p>
          </div>
        </CardHeader>

        <CardContent className="space-y-6">
          {errorMessage && (
            <Alert variant="destructive">
              <AlertDescription>{errorMessage}</AlertDescription>
            </Alert>
          )}

          <Form {...form}>
            <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-4">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <FormField
                  control={form.control}
                  name="firstName"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>First Name</FormLabel>
                      <FormControl>
                        <div className="relative">
                          <User className="absolute left-3 top-1/2 transform -translate-y-1/2 h-4 w-4 text-muted-foreground" />
                          <Input
                            {...field}
                            type="text"
                            className="pl-10"
                            placeholder="First name"
                          />
                        </div>
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                <FormField
                  control={form.control}
                  name="lastName"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Last Name</FormLabel>
                      <FormControl>
                        <div className="relative">
                          <User className="absolute left-3 top-1/2 transform -translate-y-1/2 h-4 w-4 text-muted-foreground" />
                          <Input
                            {...field}
                            type="text"
                            className="pl-10"
                            placeholder="Last name"
                          />
                        </div>
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />
              </div>

              <FormField
                control={form.control}
                name="username"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Username</FormLabel>
                    <FormControl>
                      <div className="relative">
                        <User className="absolute left-3 top-1/2 transform -translate-y-1/2 h-4 w-4 text-muted-foreground" />
                        <Input
                          {...field}
                          type="text"
                          className="pl-10"
                          placeholder="Choose a username"
                        />
                      </div>
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />

              <FormField
                control={form.control}
                name="email"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Email</FormLabel>
                    <FormControl>
                      <div className="relative">
                        <Mail className="absolute left-3 top-1/2 transform -translate-y-1/2 h-4 w-4 text-muted-foreground" />
                        <Input
                          {...field}
                          type="email"
                          className="pl-10"
                          placeholder="Your email address"
                        />
                      </div>
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />

              <FormField
                control={form.control}
                name="phoneNumber"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Phone Number</FormLabel>
                    <FormControl>
                      <div className="relative">
                        <Phone className="absolute left-3 top-1/2 transform -translate-y-1/2 h-4 w-4 text-muted-foreground" />
                        <Input
                          {...field}
                          type="text"
                          className="pl-10"
                          placeholder="Your phone number"
                        />
                      </div>
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />

              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <FormField
                  control={form.control}
                  name="password"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Password</FormLabel>
                      <FormControl>
                        <div className="relative">
                          <Lock className="absolute left-3 top-1/2 transform -translate-y-1/2 h-4 w-4 text-muted-foreground" />
                          <Input
                            {...field}
                            type="password"
                            className="pl-10"
                            placeholder="Create password"
                          />
                        </div>
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                <FormField
                  control={form.control}
                  name="confirmPassword"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Confirm Password</FormLabel>
                      <FormControl>
                        <div className="relative">
                          <Lock className="absolute left-3 top-1/2 transform -translate-y-1/2 h-4 w-4 text-muted-foreground" />
                          <Input
                            {...field}
                            type="password"
                            className="pl-10"
                            placeholder="Confirm password"
                          />
                        </div>
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />
              </div>

              <Button
                type="submit"
                className="w-full"
                size="lg"
                disabled={isRegistering}
              >
                {isRegistering ? (
                  <>
                    <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                    Creating Account...
                  </>
                ) : (
                  <>
                    <UserPlus className="mr-2 h-4 w-4" />
                    Register
                  </>
                )}
              </Button>

              <div className="text-center">
                <p className="text-sm text-muted-foreground">
                  Already have an account?{" "}
                  <Link
                    href="/login"
                    className="text-primary hover:underline font-medium"
                  >
                    Sign in
                  </Link>
                </p>
              </div>
            </form>
          </Form>
        </CardContent>
      </Card>
    </div>
  );
};

export default withGuestOnly(Register);
