// frontend/src/components/admin/ExportDropdown.vue
<template>
  <Dropdown
    :button-class="buttonClass"
    :disabled="isExporting"
    @open="$emit('open')"
    @close="$emit('close')"
  >
    <template #button>
      <i class="bi bi-download me-1"></i>
      <span v-if="isExporting">
        <span class="spinner-border spinner-border-sm me-1" role="status" aria-hidden="true"></span>
        Exporting...
      </span>
      <span v-else>Export</span>
    </template>
    
    <template #menu="{ close }">
      <li>
        <button 
          class="dropdown-item" 
          type="button"
          @click="handleExport('csv', close)" 
          :disabled="isExporting"
        >
          <i class="bi bi-filetype-csv me-2"></i>Export as CSV
        </button>
      </li>
      <li>
        <button 
          class="dropdown-item" 
          type="button"
          @click="handleExport('excel', close)" 
          :disabled="isExporting"
        >
          <i class="bi bi-filetype-xlsx me-2"></i>Export as Excel
        </button>
      </li>
    </template>
  </Dropdown>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import Dropdown from '../common/Dropdown.vue';

interface Props {
  isExporting?: boolean;
  variant?: 'primary' | 'secondary' | 'success' | 'danger' | 'warning' | 'info' | 'light' | 'dark';
  outline?: boolean;
}

const props = withDefaults(defineProps<Props>(), {
  isExporting: false,
  variant: 'success',
  outline: true
});

const emit = defineEmits<{
  export: [fileType: 'csv' | 'excel']
  open: []
  close: []
}>();

const buttonClass = computed(() => {
  const baseClass = 'btn dropdown-toggle';
  const variantClass = props.outline ? `btn-outline-${props.variant}` : `btn-${props.variant}`;
  return `${baseClass} ${variantClass}`;
});

const handleExport = (fileType: 'csv' | 'excel', closeDropdown: () => void) => {
  closeDropdown();
  emit('export', fileType);
};
</script>

// frontend/src/components/admin/ExportDropdown.tsx
'use client';

import React, { useState } from 'react';
import { Button } from '@/components/ui/button';
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from '@/components/ui/dropdown-menu';
import { Download, FileText, FileSpreadsheet, FileImage, Loader2, ChevronDown } from 'lucide-react';

interface ExportDropdownProps {
  isExporting?: boolean;
  variant?: 'primary' | 'secondary' | 'success' | 'danger' | 'warning' | 'info' | 'light' | 'dark';
  outline?: boolean;
  onExport: (fileType: 'csv' | 'excel' | 'pdf') => void;
  onOpen?: () => void;
  onClose?: () => void;
}

const ExportDropdown: React.FC<ExportDropdownProps> = ({
  isExporting = false,
  variant = 'success',
  outline = true,
  onExport,
  onOpen,
  onClose
}) => {
  const [isOpen, setIsOpen] = useState(false);

  const getVariant = () => {
    if (outline) {
      return 'outline';
    }
    switch (variant) {
      case 'danger':
        return 'destructive';
      case 'secondary':
        return 'secondary';
      case 'success':
        return 'default';
      default:
        return 'default';
    }
  };

  const handleExport = (fileType: 'csv' | 'excel' | 'pdf') => {
    onExport(fileType);
  };

  const handleOpenChange = (open: boolean) => {
    setIsOpen(open);
    if (open) {
      onOpen?.();
    } else {
      onClose?.();
    }
  };

  return (
    <DropdownMenu open={isOpen} onOpenChange={handleOpenChange}>
      <DropdownMenuTrigger asChild>
        <Button
          variant={getVariant()}
          disabled={isExporting}
          className="gap-2"
        >
          {isExporting ? (
            <>
              <Loader2 className="h-4 w-4 animate-spin" />
              Exporting...
            </>
          ) : (
            <>
              <Download className="h-4 w-4" />
              Export
              <ChevronDown className="h-4 w-4" />
            </>
          )}
        </Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent>
        <DropdownMenuItem 
          onClick={() => handleExport('csv')} 
          disabled={isExporting}
          className="gap-2"
        >
          <FileText className="h-4 w-4" />
          Export as CSV
        </DropdownMenuItem>
        <DropdownMenuItem 
          onClick={() => handleExport('excel')} 
          disabled={isExporting}
          className="gap-2"
        >
          <FileSpreadsheet className="h-4 w-4" />
          Export as Excel
        </DropdownMenuItem>
        <DropdownMenuItem 
          onClick={() => handleExport('pdf')} 
          disabled={isExporting}
          className="gap-2"
        >
          <FileImage className="h-4 w-4" />
          Export as PDF
        </DropdownMenuItem>
      </DropdownMenuContent>
    </DropdownMenu>
  );
};

export default ExportDropdown;
