// frontend-bk/src/components/front/Cart.vue
<template>
  <div class="shopping-cart p-4 border bg-light shadow-sm rounded">
    <h5 class="mb-4 text-center">Your Cart</h5>

    <ul v-if="cart.length" class="list-group mb-3">
      <li
        v-for="item in cart"
        :key="item.product.id"
        class="list-group-item border-0 border-bottom py-3"
      >
        <div class="d-flex align-items-center gap-3">
          <!-- Remove button -->
          <button
            @click="removeFromCart(item.product.id)"
            class="btn btn-link text-danger p-0 fs-5"
            :disabled="isProcessing"
          >
            <i class="bi bi-x"></i>
          </button>

          <!-- Product image -->
          <img
            :src="getProductImageUrl(item.product.image)"
            :alt="item.product.name"
            class="cart-item-image"
          />

          <!-- Product name -->
          <div class="flex-grow-1">
            <strong>{{ item.product.name }}</strong>
          </div>

          <!-- Quantity controls -->
          <div class="d-flex align-items-center gap-2">
            <button
              @click="decreaseQuantity(item)"
              class="btn btn-sm btn-outline-secondary"
              :disabled="isProcessing"
            >
              -
            </button>
            <input
              type="number"
              v-model.number="item.quantity"
              class="form-control form-control-sm text-center"
              style="width: 40px"
              min="1"
              @change="updateQuantity(item.product.id, item.quantity)"
              :disabled="isProcessing"
            />
            <button
              @click="increaseQuantity(item)"
              class="btn btn-sm btn-outline-secondary"
              :disabled="isProcessing"
            >
              +
            </button>
          </div>

          <!-- Price -->
          <span class="fw-bold">${{ formatCurrency(cartStore.getItemTotal(item)) }}</span>
        </div>
      </li>
    </ul>

    <p v-else class="text-center text-muted">Your cart is empty.</p>

    <div v-if="cart.length" class="d-flex justify-content-between mt-3">
      <span class="fw-bold">Total:</span>
      <span class="fw-bold">${{ formatCurrency(total) }}</span>
    </div>

    <button
      @click="handlePlaceOrder"
      class="btn btn-success w-100 mt-4"
      :disabled="!cart.length || isProcessing"
    >
      {{ isProcessing ? "Processing..." : "Place Order" }}
    </button>
  </div>
</template>

<script setup lang="ts">
import type { PlaceOrderItemRequest } from '@/interfaces/order.interface';
import { orderService } from '@/services';
import { useCartStore, type CartItem } from '@/stores/cart.store';
import { useUserStore } from '@/stores/user.store';
import { formatCurrency } from '@/utils/formatter.util';
import { getProductImageUrl } from '@/utils/productImage.util';
import { computed, ref } from 'vue';
import { useRouter } from 'vue-router';

const isProcessing = ref(false);
const cartStore = useCartStore();
const userStore = useUserStore();
const router = useRouter();

const cart = computed(() => cartStore.cart);
const total = computed(() => cartStore.getTotal());

function removeFromCart(productId: number) {
  cartStore.removeFromCart(productId);
}

function increaseQuantity(item: CartItem) {
  cartStore.updateQuantity(item.product.id, item.quantity + 1);
}

function decreaseQuantity(item: CartItem) {
  if (item.quantity <= 1) {
    cartStore.removeFromCart(item.product.id);
  } else {
    cartStore.updateQuantity(item.product.id, item.quantity - 1);
  }
}

function updateQuantity(productId: number, quantity: number) {
  cartStore.updateQuantity(productId, quantity > 0 ? quantity : 1);
}

async function handlePlaceOrder() {
  if (!cart.value.length || isProcessing.value) return;

  if (!userStore.isAuthenticated) {
    router.push({ name: 'login' });
    return
  }

  try {
    isProcessing.value = true;

    const orderItems = cart.value.map((cartItem) => ({
      productId: cartItem.product.id,
      quantity: cartItem.quantity,
    } as PlaceOrderItemRequest));

    const response = await orderService.placeOrder({orderItems});
    
    if (response.success && response.data) {
      cartStore.currentOrderId = response.data;
      cartStore.clearCart();
    } else {
      console.error('Failed to place order:', response.errorMessage);
    }
  } catch (err: any) {
    console.error('Failed to place order:', err?.message || err);
  } finally {
    isProcessing.value = false;
  }
}
</script>

<style scoped>
.shopping-cart {
  background-color: #f8f9fa;
  border-radius: 5px;
}

.cart-item-image {
  width: 60px;
  height: 60px;
  object-fit: cover;
  border-radius: 4px;
}

input[type='number']::-webkit-inner-spin-button,
input[type='number']::-webkit-outer-spin-button {
  -webkit-appearance: none;
  margin: 0;
}
</style>

// frontend/src/components/front/Cart.tsx
import { PlaceOrderItemRequest } from "@/interfaces";
import { orderService } from "@/services";
import { CartItem, useCartStore, useUserStore } from "@/stores";
import { formatCurrency } from "@/utils/formatter.util";
import Image from "next/image";
import { useRouter } from "next/navigation";
import React, { useState } from "react";
import { toast } from "sonner";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { X, Minus, Plus } from "lucide-react";

const Cart: React.FC = () => {
  const [isProcessing, setIsProcessing] = useState(false);
  const {
    cart,
    getTotal,
    getItemTotal,
    removeFromCart,
    updateQuantity,
    clearCart,
    setCurrentOrderId,
  } = useCartStore();
  const { isAuthenticated } = useUserStore();
  const router = useRouter();

  const total = getTotal();

  const handleRemoveFromCart = (productId: number) => {
    removeFromCart(productId);
  };

  const handleIncreaseQuantity = (item: CartItem) => {
    updateQuantity(item.productId, item.quantity + 1);
  };

  const handleDecreaseQuantity = (item: CartItem) => {
    if (item.quantity <= 1) {
      removeFromCart(item.productId);
    } else {
      updateQuantity(item.productId, item.quantity - 1);
    }
  };

  const handlePlaceOrder = async () => {
    if (!cart.length || isProcessing) return;

    if (!isAuthenticated) {
      router.push("/login");
      return;
    }

    try {
      setIsProcessing(true);

      const orderItems: PlaceOrderItemRequest[] = cart.map(
        (cartItem: CartItem) => ({
          productId: cartItem.productId,
          quantity: cartItem.quantity,
        })
      );

      const response = await orderService.placeOrder({ orderItems });

      if (response.success && response.data) {
        setCurrentOrderId(response.data.orderId);
        clearCart();
        toast.success("Order placed successfully!");
      } else {
        toast.error(response.errorMessage || "Failed to place order");
      }
    } catch (err: unknown) {
      const errorMessage = err instanceof Error ? err.message : "Unknown error";
      toast.error("Failed to place order: " + errorMessage);
    } finally {
      setIsProcessing(false);
    }
  };

  return (
    <Card className="shopping-cart shadow-sm">
      <CardHeader>
        <CardTitle className="text-center">Your Cart</CardTitle>
      </CardHeader>
      <CardContent>
        {cart.length > 0 ? (
          <div className="space-y-3 mb-6">
            {cart.map((item: CartItem) => (
              <div
                key={item.productId}
                className="border-b border-gray-200 last:border-b-0 py-3"
              >
                <div className="flex items-center gap-3">
                  {/* Remove button */}
                  <Button
                    onClick={() => handleRemoveFromCart(item.productId)}
                    variant="ghost"
                    size="sm"
                    className="text-red-500 hover:text-red-700 p-1 h-auto"
                    disabled={isProcessing}
                  >
                    <X className="h-4 w-4" />
                  </Button>

                  {/* Product image */}
                  <Image
                    src={item.imageUrl || "/placeholder-image.jpg"}
                    alt={item.name}
                    className="cart-item-image"
                    width={60}
                    height={60}
                    style={{
                      objectFit: "cover",
                      borderRadius: "4px",
                    }}
                  />

                  {/* Product name */}
                  <div className="flex-1">
                    <span className="font-semibold">{item.name}</span>
                  </div>

                  {/* Quantity controls */}
                  <div className="flex items-center gap-2">
                    <Button
                      onClick={() => handleDecreaseQuantity(item)}
                      variant="outline"
                      size="sm"
                      className="h-8 w-8 p-0"
                      disabled={isProcessing}
                    >
                      <Minus className="h-3 w-3" />
                    </Button>
                    <Input
                      type="number"
                      value={item.quantity}
                      onChange={(e) =>
                        updateQuantity(
                          item.productId,
                          parseInt(e.target.value) || 1
                        )
                      }
                      className="w-12 h-8 text-center text-sm"
                      min="1"
                      disabled={isProcessing}
                    />
                    <Button
                      onClick={() => handleIncreaseQuantity(item)}
                      variant="outline"
                      size="sm"
                      className="h-8 w-8 p-0"
                      disabled={isProcessing}
                    >
                      <Plus className="h-3 w-3" />
                    </Button>
                  </div>

                  {/* Price */}
                  <span className="font-bold">
                    ${formatCurrency(getItemTotal(item.productId))}
                  </span>
                </div>
              </div>
            ))}
          </div>
        ) : (
          <p className="text-center text-gray-500 py-8">Your cart is empty.</p>
        )}

        {cart.length > 0 && (
          <div className="flex justify-between items-center pt-4 border-t border-gray-200">
            <span className="font-bold text-lg">Total:</span>
            <span className="font-bold text-lg">${formatCurrency(total)}</span>
          </div>
        )}

        <Button
          onClick={handlePlaceOrder}
          className="w-full mt-6"
          disabled={!cart.length || isProcessing}
        >
          {isProcessing ? "Processing..." : "Place Order"}
        </Button>
      </CardContent>
    </Card>
  );
};

export default Cart;
