// frontend/src/components/admin/ProductList.tsx
"use client";

import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Checkbox } from "@/components/ui/checkbox";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Pagination,
  PaginationContent,
  PaginationItem,
  PaginationLink,
  PaginationNext,
  PaginationPrevious,
} from "@/components/ui/pagination";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { Metadata } from "@/interfaces";
import {
  FileType,
  PRODUCT_STATUSES,
  type Brand,
  type Category,
  type ExportProductFilters,
  type ListProductFilters,
  type Product,
} from "@/interfaces/product.interface";
import { productService } from "@/services";
import { useUserStore } from "@/stores/user.store";
import { formatCurrency, getProductStatusBadge } from "@/utils/formatter.util";
import { getProductImageUrl } from "@/utils/productImage.util";
import {
  Edit,
  Loader2,
  Plus,
  RotateCcw,
  Search,
  Trash2,
  Upload,
} from "lucide-react";
import Image from "next/image";
import { useRouter } from "next/navigation";
import React, { useCallback, useEffect, useState } from "react";
import { toast } from "sonner";
import ExportDropdown from "./ExportDropdown";
import ImportProductModal from "./ImportProductModal";

interface ProductListProps {
  className?: string;
}

interface ActiveStates {
  active: boolean;
  inactive: boolean;
}

const ProductList: React.FC<ProductListProps> = ({ className = "" }) => {
  const router = useRouter();
  const { profile } = useUserStore();

  // State
  const [activeStates, setActiveStates] = useState<ActiveStates>({
    active: true,
    inactive: true,
  });
  const [brands, setBrands] = useState<Brand[]>([]);
  const [categories, setCategories] = useState<Category[]>([]);
  const [products, setProducts] = useState<Product[]>([]);
  const [isLoadingBrands, setIsLoadingBrands] = useState(false);
  const [isLoadingCategories, setIsLoadingCategories] = useState(false);
  const [isLoadingProducts, setIsLoadingProducts] = useState(false);
  const [isExporting, setIsExporting] = useState(false);
  const [isImporting] = useState(false);
  const [showImportModal, setShowImportModal] = useState(false);
  const [hasInitialLoad, setHasInitialLoad] = useState(false);
  const [metadata, setMetadata] = useState<Metadata>({
    currentPage: 1,
    pageSize: 20,
    totalPages: 1,
    totalRecords: 0,
  });
  const [filters, setFilters] = useState<ListProductFilters>({
    id: undefined,
    keyword: undefined,
    minPrice: undefined,
    maxPrice: undefined,
    status: undefined,
    availableFrom: undefined,
    isActive: undefined,
    brandId: "",
    categoryIds: [],
    page: 1,
    size: 20,
  });

  // Redirect if not admin
  useEffect(() => {
    if (!profile || profile.role !== "ADMIN") {
      router.push("/login");
    }
  }, [profile, router]);

  const loadBrands = useCallback(async () => {
    setIsLoadingBrands(true);
    try {
      const { data } = await productService.listBrand();
      setBrands(data);
    } catch {
      toast.error("Failed to load brands");
    } finally {
      setIsLoadingBrands(false);
    }
  }, []);

  const loadCategories = useCallback(async () => {
    setIsLoadingCategories(true);
    try {
      const { data } = await productService.listCategory();
      setCategories(data);
    } catch {
      toast.error("Failed to load categories");
    } finally {
      setIsLoadingCategories(false);
    }
  }, []);

  const handleActiveStateChange = useCallback(() => {
    let isActive: boolean | undefined;
    if (activeStates.active && activeStates.inactive) {
      isActive = undefined;
    } else if (activeStates.active) {
      isActive = true;
    } else if (activeStates.inactive) {
      isActive = false;
    } else {
      isActive = undefined;
    }
    setFilters((prev) => ({ ...prev, isActive }));
  }, [activeStates]);

  useEffect(() => {
    handleActiveStateChange();
  }, [handleActiveStateChange]);

  const applyFilters = useCallback(
    async (page: number, currentFilters?: ListProductFilters) => {
      if (isLoadingProducts) return;

      setIsLoadingProducts(true);
      try {
        const filtersToUse = currentFilters || filters;
        const updatedFilters = { ...filtersToUse, page };
        setFilters(updatedFilters);
        setMetadata((prev) => ({ ...prev, currentPage: page }));

        // Clean up empty or undefined filters
        const apiFilters: ListProductFilters = { ...updatedFilters };
        Object.keys(apiFilters).forEach((key) => {
          const typedKey = key as keyof ListProductFilters;
          if (
            apiFilters[typedKey] === "" ||
            apiFilters[typedKey] === undefined
          ) {
            delete apiFilters[typedKey];
          }
        });

        const response = await productService.listProduct(apiFilters);
        setProducts(response.data);
        setMetadata((prev) => ({ ...prev, ...response.metadata }));
      } catch {
        toast.error("Failed to load products");
      } finally {
        setIsLoadingProducts(false);
      }
    },
    [filters, isLoadingProducts]
  );

  const changePage = useCallback(
    (newPage: number) => {
      if (newPage >= 1 && newPage <= metadata.totalPages) {
        applyFilters(newPage);
      }
    },
    [metadata.totalPages, applyFilters]
  );

  const resetFilters = () => {
    const resetFiltersData: ListProductFilters = {
      id: undefined,
      keyword: undefined,
      minPrice: undefined,
      maxPrice: undefined,
      status: "",
      availableFrom: undefined,
      isActive: undefined,
      brandId: "",
      categoryIds: [],
      page: 1,
      size: 20,
    };
    setActiveStates({ active: true, inactive: true });
    setFilters(resetFiltersData);
    applyFilters(1, resetFiltersData);
  };

  const handleFilterChange = (
    field: keyof ListProductFilters,
    value: string | number | boolean | undefined | number[]
  ) => {
    setFilters((prev) => ({ ...prev, [field]: value }));
  };

  const handleSearch = () => {
    applyFilters(1);
  };

  const handleDelete = useCallback(
    async (productId: number) => {
      if (!confirm("Are you sure you want to delete this product?")) return;

      try {
        await productService.deleteProduct(productId);
        toast.success("Product deleted successfully");
        applyFilters(metadata.currentPage);
      } catch {
        toast.error("Failed to delete product");
      }
    },
    [metadata.currentPage, applyFilters]
  );

  const handleExport = useCallback(
    async (fileType: "csv" | "excel" | "pdf") => {
      if (isExporting) return;

      setIsExporting(true);
      try {
        const exportFilters: ExportProductFilters = {
          id: filters.id,
          keyword: filters.keyword,
          minPrice: filters.minPrice,
          maxPrice: filters.maxPrice,
          status: filters.status,
          availableFrom: filters.availableFrom,
          isActive: filters.isActive,
          brandId: filters.brandId,
          categoryIds: filters.categoryIds,
          fileType: FileType[fileType.toUpperCase() as keyof typeof FileType],
        };
        await productService.exportProduct(exportFilters);
        toast.success(
          `Products exported successfully as ${fileType.toUpperCase()}`
        );
      } catch (error) {
        console.error("Export failed:", error);
        toast.error("Failed to export products");
      } finally {
        setIsExporting(false);
      }
    },
    [isExporting, filters]
  );

  const handleImportClick = useCallback(() => {
    setShowImportModal(true);
  }, []);

  const handleImportSuccess = useCallback(() => {
    setShowImportModal(false);
    applyFilters(1);
  }, [applyFilters]);

  // Load initial data
  useEffect(() => {
    const loadInitialData = async () => {
      try {
        await Promise.all([loadBrands(), loadCategories(), applyFilters(1)]);
      } finally {
        setIsLoadingProducts(false);
      }
    };

    if (profile && profile.role === "ADMIN" && !hasInitialLoad) {
      loadInitialData();
      setHasInitialLoad(true);
    }
  }, [profile, hasInitialLoad]);

  if (!profile || profile.role !== "ADMIN") {
    return null;
  }

  return (
    <div className={`space-y-6 ${className}`}>
      {/* Header */}
      <div className="flex items-center justify-start">
        <div className="flex gap-2">
          <Button
            variant="outline"
            onClick={handleImportClick}
            disabled={isImporting}
          >
            <Upload className="h-4 w-4 mr-2" />
            {isImporting ? (
              <>
                <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                Importing...
              </>
            ) : (
              "Import"
            )}
          </Button>
          <ExportDropdown isExporting={isExporting} onExport={handleExport} />
          <Button onClick={() => router.push("/admin/product/add")}>
            <Plus className="h-4 w-4 mr-2" />
            Add New Product
          </Button>
        </div>
      </div>

      {/* Filters Card */}
      <Card>
        <CardHeader>
          <CardTitle>Product Filters</CardTitle>
        </CardHeader>
        <CardContent>
          {/* Row 1: Product ID, Product Keyword, Min Price, Max Price */}
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
            <div className="space-y-2">
              <Label htmlFor="productId">Product ID</Label>
              <Input
                type="number"
                id="productId"
                placeholder="Enter product ID"
                value={filters.id || ""}
                onChange={(e) =>
                  handleFilterChange(
                    "id",
                    e.target.value ? Number(e.target.value) : undefined
                  )
                }
              />
            </div>

            <div className="space-y-2">
              <Label htmlFor="keyword">Product Keyword</Label>
              <Input
                type="text"
                id="keyword"
                placeholder="Search by product name, description, or an attribute"
                value={filters.keyword || ""}
                onChange={(e) =>
                  handleFilterChange("keyword", e.target.value || undefined)
                }
              />
            </div>

            <div className="space-y-2">
              <Label htmlFor="minPrice">Min Price</Label>
              <Input
                type="number"
                step="0.01"
                id="minPrice"
                placeholder="Min price"
                value={filters.minPrice || ""}
                onChange={(e) =>
                  handleFilterChange(
                    "minPrice",
                    e.target.value ? Number(e.target.value) : undefined
                  )
                }
              />
            </div>

            <div className="space-y-2">
              <Label htmlFor="maxPrice">Max Price</Label>
              <Input
                type="number"
                step="0.01"
                id="maxPrice"
                placeholder="Max price"
                value={filters.maxPrice || ""}
                onChange={(e) =>
                  handleFilterChange(
                    "maxPrice",
                    e.target.value ? Number(e.target.value) : undefined
                  )
                }
              />
            </div>
          </div>

          {/* Row 2: Product Status, Available From, Activity */}
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4 mt-5">
            <div className="space-y-2">
              <Label htmlFor="status">Product Status</Label>
              <Select
                value={filters.status}
                onValueChange={(value) => handleFilterChange("status", value)}
              >
                <SelectTrigger>
                  <SelectValue placeholder="All Statuses" />
                </SelectTrigger>
                <SelectContent>
                  {PRODUCT_STATUSES.map((status) => (
                    <SelectItem key={status} value={status}>
                      {status}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>

            <div className="space-y-2">
              <Label htmlFor="availableFrom">Available From</Label>
              <Input
                type="date"
                id="availableFrom"
                value={filters.availableFrom || ""}
                onChange={(e) =>
                  handleFilterChange(
                    "availableFrom",
                    e.target.value || undefined
                  )
                }
              />
            </div>

            <div className="space-y-2">
              <Label>Activity</Label>
              <div className="border rounded p-3 flex items-center space-x-6">
                <div className="flex items-center space-x-2">
                  <Checkbox
                    id="activeCheck"
                    checked={activeStates.active}
                    onCheckedChange={(checked) =>
                      setActiveStates((prev) => ({
                        ...prev,
                        active: checked as boolean,
                      }))
                    }
                  />
                  <Label htmlFor="activeCheck">Active</Label>
                </div>
                <div className="flex items-center space-x-2">
                  <Checkbox
                    id="inactiveCheck"
                    checked={activeStates.inactive}
                    onCheckedChange={(checked) =>
                      setActiveStates((prev) => ({
                        ...prev,
                        inactive: checked as boolean,
                      }))
                    }
                  />
                  <Label htmlFor="inactiveCheck">Inactive</Label>
                </div>
              </div>
            </div>
          </div>

          {/* Row 3: Brand, Categories */}
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4 mt-4">
            <div className="space-y-2">
              <Label htmlFor="brandId">Brand</Label>
              {isLoadingBrands ? (
                <div className="flex items-center justify-center py-2">
                  <Loader2 className="h-4 w-4 animate-spin" />
                </div>
              ) : (
                <Select
                  value={filters.brandId || ""}
                  onValueChange={(value) =>
                    handleFilterChange("brandId", value)
                  }
                >
                  <SelectTrigger>
                    <SelectValue placeholder="All Brands" />
                  </SelectTrigger>
                  <SelectContent>
                    {brands.map((brand) => (
                      <SelectItem key={brand.id} value={brand.id.toString()}>
                        {brand.name}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              )}
            </div>

            <div className="space-y-2">
              <Label>Categories</Label>
              {isLoadingCategories ? (
                <div className="flex items-center justify-center py-2">
                  <Loader2 className="h-4 w-4 animate-spin" />
                </div>
              ) : (
                <Select value="placeholder" onValueChange={() => {}}>
                  <SelectTrigger>
                    <SelectValue>
                      {filters.categoryIds && filters.categoryIds.length > 0
                        ? `${filters.categoryIds.length} categories selected`
                        : "All Categories"}
                    </SelectValue>
                  </SelectTrigger>
                  <SelectContent>
                    {categories.map((category) => (
                      <label
                        key={category.id}
                        className="flex items-center space-x-2 cursor-pointer hover:bg-gray-50 p-1 rounded"
                      >
                        <input
                          type="checkbox"
                          className="rounded border-gray-300 text-blue-600 focus:ring-blue-500"
                          checked={
                            filters.categoryIds?.includes(category.id) || false
                          }
                          onChange={(e) => {
                            const currentCategories = filters.categoryIds || [];
                            if (e.target.checked) {
                              handleFilterChange("categoryIds", [
                                ...currentCategories,
                                category.id,
                              ]);
                            } else {
                              handleFilterChange(
                                "categoryIds",
                                currentCategories.filter(
                                  (id) => id !== category.id
                                )
                              );
                            }
                          }}
                        />
                        <span className="text-sm">{category.name}</span>
                      </label>
                    ))}
                  </SelectContent>
                </Select>
              )}
            </div>
          </div>

          <div className="flex justify-start space-x-2 mt-4">
            <Button onClick={handleSearch} disabled={isLoadingProducts}>
              <Search className="h-4 w-4 mr-2" />
              Search
            </Button>
            <Button
              variant="outline"
              onClick={resetFilters}
              disabled={isLoadingProducts}
            >
              <RotateCcw className="h-4 w-4 mr-2" />
              Reset
            </Button>
          </div>
        </CardContent>
      </Card>

      {/* Products Table */}
      <Card>
        <CardHeader>
          <CardTitle>Product Results</CardTitle>
        </CardHeader>
        <CardContent>
          {isLoadingProducts ? (
            <div className="flex flex-col items-center justify-center py-12">
              <Loader2 className="h-8 w-8 animate-spin text-primary" />
              <p className="mt-2 text-muted-foreground">Loading products...</p>
            </div>
          ) : (
            <div className="rounded-md border">
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>ID</TableHead>
                    <TableHead>Name</TableHead>
                    <TableHead>Image</TableHead>
                    <TableHead>Price</TableHead>
                    <TableHead>Quantity</TableHead>
                    <TableHead>Status</TableHead>
                    <TableHead>Actions</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {products.length === 0 ? (
                    <TableRow>
                      <TableCell
                        colSpan={7}
                        className="text-center py-8 text-muted-foreground"
                      >
                        No products found
                      </TableCell>
                    </TableRow>
                  ) : (
                    products.map((product) => (
                      <TableRow key={product.id}>
                        <TableCell>{product.id}</TableCell>
                        <TableCell>{product.name}</TableCell>
                        <TableCell>
                          <Image
                            src={getProductImageUrl(product.image)}
                            alt={product.name}
                            width={48}
                            height={48}
                            className="rounded object-cover"
                          />
                        </TableCell>
                        <TableCell>${formatCurrency(product.price)}</TableCell>
                        <TableCell>{product.quantity}</TableCell>
                        <TableCell>
                          {getProductStatusBadge(product.status)}
                        </TableCell>
                        <TableCell>
                          <div className="flex items-center gap-2">
                            <Button
                              variant="outline"
                              size="sm"
                              onClick={() =>
                                router.push(`/admin/product/edit/${product.id}`)
                              }
                            >
                              <Edit className="h-4 w-4" />
                            </Button>
                            <Button
                              variant="outline"
                              size="sm"
                              onClick={() => handleDelete(product.id)}
                            >
                              <Trash2 className="h-4 w-4" />
                            </Button>
                          </div>
                        </TableCell>
                      </TableRow>
                    ))
                  )}
                </TableBody>
              </Table>
            </div>
          )}
        </CardContent>
      </Card>

      {/* Pagination */}
      {metadata.totalPages > 1 && (
        <div className="flex items-center justify-between">
          <div className="text-sm text-muted-foreground">
            Page {metadata.currentPage} of {metadata.totalPages} (
            {metadata.totalRecords} records)
          </div>
          <Pagination>
            <PaginationContent>
              <PaginationItem>
                <PaginationPrevious
                  href="#"
                  onClick={(e) => {
                    e.preventDefault();
                    if (metadata.currentPage > 1) {
                      changePage(metadata.currentPage - 1);
                    }
                  }}
                  className={
                    metadata.currentPage <= 1
                      ? "pointer-events-none opacity-50"
                      : ""
                  }
                />
              </PaginationItem>

              {/* Page numbers */}
              {Array.from(
                { length: Math.min(5, metadata.totalPages) },
                (_, i) => {
                  const pageNumber =
                    Math.max(
                      1,
                      Math.min(
                        metadata.totalPages - 4,
                        metadata.currentPage - 2
                      )
                    ) + i;

                  if (pageNumber <= metadata.totalPages) {
                    return (
                      <PaginationItem key={pageNumber}>
                        <PaginationLink
                          href="#"
                          onClick={(e) => {
                            e.preventDefault();
                            changePage(pageNumber);
                          }}
                          isActive={pageNumber === metadata.currentPage}
                        >
                          {pageNumber}
                        </PaginationLink>
                      </PaginationItem>
                    );
                  }
                  return null;
                }
              )}

              <PaginationItem>
                <PaginationNext
                  href="#"
                  onClick={(e) => {
                    e.preventDefault();
                    if (metadata.currentPage < metadata.totalPages) {
                      changePage(metadata.currentPage + 1);
                    }
                  }}
                  className={
                    metadata.currentPage >= metadata.totalPages
                      ? "pointer-events-none opacity-50"
                      : ""
                  }
                />
              </PaginationItem>
            </PaginationContent>
          </Pagination>
        </div>
      )}

      {/* Import Modal */}
      {showImportModal && (
        <ImportProductModal
          isVisible={showImportModal}
          onClose={() => setShowImportModal(false)}
          onImportSuccess={handleImportSuccess}
        />
      )}
    </div>
  );
};

export default ProductList;

// frontend/src/pages/admin/ProductList.vue
<template>
  <div class="container-fluid px-5 py-4">
    <div class="d-flex justify-content-between align-items-center mb-4">
      <div>
        <h3 class="mb-1">Product Management</h3>
        <p class="text-muted mb-0">Manage your product catalog</p>
      </div>
      <div class="d-flex gap-2">
        <button 
          class="btn btn-outline-primary" 
          @click="handleImportClick"
          :disabled="isImporting"
        >
          <i class="bi bi-upload me-1"></i>
          <span v-if="isImporting">
            <span class="spinner-border spinner-border-sm me-1" role="status" aria-hidden="true"></span>
            Importing...
          </span>
          <span v-else>Import</span>
        </button>
        <ExportDropdown 
          :is-exporting="isExporting"
          @export="handleExport"
        />
        <button class="btn btn-success" @click="router.push({ name: 'adminProductAdd' })">
          <i class="bi bi-plus-lg"></i> Add New Product
        </button>
      </div>
    </div>

    <!-- Filters Card -->
    <div class="card mb-4 shadow-sm">
      <div class="card-header bg-light py-3">
        <h5 class="mb-0">Search Filters</h5>
      </div>
      <div class="card-body p-4">
        <form @submit.prevent="applyFilters(1)">
          <div class="row g-4">
            <div class="col-md-6">
              <label for="productId" class="form-label">Product ID</label>
              <input
                id="productId"
                v-model.trim="filters.id"
                type="text"
                placeholder="Enter product ID..."
                class="form-control"
              />
            </div>

            <div class="col-md-6">
              <label for="keyword" class="form-label">Search</label>
              <input
                id="keyword"
                v-model.trim="filters.keyword"
                type="text"
                placeholder="Search by product name or description..."
                class="form-control"
              />
            </div>

            <div class="col-md-6">
              <label class="form-label">Price Range</label>
              <div class="input-group">
                <input
                  v-model.number="filters.minPrice"
                  type="number"
                  step="0.01"
                  placeholder="Min price"
                  class="form-control"
                />
                <span class="input-group-text bg-light">to</span>
                <input
                  v-model.number="filters.maxPrice"
                  type="number"
                  step="0.01"
                  placeholder="Max price"
                  class="form-control"
                />
              </div>
            </div>

            <div class="col-md-6">
              <label for="status" class="form-label">Status</label>
              <select id="status" v-model="filters.status" class="form-select">
                <option value="">All statuses</option>
                <option v-for="status in productStatuses" :key="status" :value="status">
                  {{ formatProductStatusLabel(status) }}
                </option>
              </select>
            </div>

            <div class="col-md-6">
              <label for="availableFrom" class="form-label">Available From</label>
              <input
                id="availableFrom"
                v-model="filters.availableFrom"
                type="date"
                class="form-control"
              />
            </div>

            <div class="col-md-6">
              <label class="form-label">Activity</label>
              <div class="border rounded p-3">
                <div class="d-flex gap-4">
                  <div class="form-check">
                    <input
                      type="checkbox"
                      class="form-check-input"
                      id="activeCheck"
                      v-model="activeStates.active"
                      @change="handleActiveStateChange"
                    />
                    <label class="form-check-label" for="activeCheck">Active</label>
                  </div>
                  <div class="form-check">
                    <input
                      type="checkbox"
                      class="form-check-input"
                      id="inactiveCheck"
                      v-model="activeStates.inactive"
                      @change="handleActiveStateChange"
                    />
                    <label class="form-check-label" for="inactiveCheck">Inactive</label>
                  </div>
                </div>
              </div>
            </div>

            <div class="col-md-6">
              <label for="brandId" class="form-label">Brand</label>
              <div v-if="isLoadingBrands" class="text-center py-2" aria-live="polite">
                <div class="spinner-border spinner-border-sm" role="status" aria-label="Loading brands">
                  <span class="visually-hidden">Loading...</span>
                </div>
              </div>
              <select
                v-else
                id="brandId"
                v-model="filters.brandId"
                class="form-select"
                :disabled="!brands.length"
              >
                <option value="">All brands</option>
                <option v-for="brand in brands" :key="brand.id" :value="brand.id">
                  {{ brand.name }}
                </option>
              </select>
            </div>

            <div class="col-md-6">
              <label for="categoryIds" class="form-label">Categories</label>
              <div v-if="isLoadingCategories" class="text-center py-2" aria-live="polite">
                <div class="spinner-border spinner-border-sm" role="status" aria-label="Loading categories">
                  <span class="visually-hidden">Loading...</span>
                </div>
              </div>
              <select
                v-else
                id="categoryIds"
                v-model="filters.categoryIds"
                multiple
                class="form-select"
                :disabled="!categories.length"
                size="3"
              >
                <option v-for="category in categories" :key="category.id" :value="category.id">
                  {{ category.name }}
                </option>
              </select>
              <small class="text-muted">Hold Ctrl/Cmd to select multiple</small>
            </div>
          </div>

          <div class="d-flex gap-2 mt-4 pt-3 border-top">
            <button type="submit" class="btn btn-primary">
              <i class="bi bi-search"></i> Search
            </button>
            <button type="button" @click="resetFilters" class="btn btn-outline-secondary">
              <i class="bi bi-arrow-counterclockwise"></i> Reset
            </button>
          </div>
        </form>
      </div>
    </div>

    <!-- Products Table -->
    <div class="card shadow-sm">
      <div class="card-header bg-light py-3">
        <h5 class="mb-0">Product List</h5>
      </div>
      <div v-if="isLoadingProducts" class="text-center py-5" aria-live="polite">
        <div class="spinner-border text-primary" role="status" aria-label="Loading products">
          <span class="visually-hidden">Loading...</span>
        </div>
      </div>
      <div v-else class="card-body p-0">
        <div class="table-responsive">
          <table class="table table-hover table-bordered mb-0">
            <thead class="table-light">
              <tr>
                <th scope="col" class="px-4">ID</th>
                <th scope="col" class="px-4">Name</th>
                <th scope="col" class="px-4">Image</th>
                <th scope="col" class="px-4">Price</th>
                <th scope="col" class="px-4">Quantity</th>
                <th scope="col" class="px-4">Status</th>
                <th scope="col" class="px-4">Actions</th>
              </tr>
            </thead>
            <tbody>
              <tr v-for="product in products" :key="product.id">
                <td class="px-4">{{ product.id }}</td>
                <td class="px-4">{{ product.name }}</td>
                <td class="px-4">
                  <img
                    :src="getProductImageUrl(product.image)"
                    :alt="product.name"
                    class="rounded"
                    style="width: 48px; height: 48px; object-fit: cover;"
                  />
                </td>
                <td class="px-4">${{ formatCurrency(product.price) }}</td>
                <td class="px-4">{{ product.quantity }}</td>
                <td class="px-4">
                  <span :class="getProductStatusBadgeClasses(product.status)">
                    {{ formatProductStatusLabel(product.status) }}
                  </span>
                </td>
                <td class="px-4">
                  <div class="d-flex gap-2">
                    <button
                      class="btn btn-sm btn-outline-secondary"
                      @click="router.push({ name: 'adminProductInfo', params: { id: product.id } })"
                    >
                      <i class="bi bi-eye me-1"></i> View
                    </button>
                    <button
                      class="btn btn-sm btn-outline-primary"
                      @click="router.push({ name: 'adminProductEdit', params: { id: product.id } })"
                    >
                      <i class="bi bi-pencil me-1"></i> Edit
                    </button>
                    <button
                      class="btn btn-sm btn-outline-danger"
                      @click="handleDelete(product.id)"
                    >
                      <i class="bi bi-trash me-1"></i> Delete
                    </button>
                  </div>
                </td>
              </tr>
            </tbody>
          </table>
        </div>

        <!-- Pagination -->
        <div class="card-footer bg-light py-3">
          <div class="d-flex justify-content-between align-items-center">
            <span class="text-muted">
              Page {{ metadata.currentPage }} of {{ metadata.totalPages }}
              <span class="ms-2">({{ metadata.totalRecords }} records)</span>
            </span>
            <div class="btn-group">
              <button
                @click="changePage(metadata.currentPage - 1)"
                :disabled="metadata.currentPage <= 1"
                class="btn btn-outline-secondary px-3"
              >
                <i class="bi bi-chevron-left me-1"></i> Previous
              </button>
              <button
                @click="changePage(metadata.currentPage + 1)"
                :disabled="metadata.currentPage >= metadata.totalPages"
                class="btn btn-outline-secondary px-3"
              >
                Next <i class="bi bi-chevron-right ms-1"></i>
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Import Modal -->
    <ImportProductModal @imported="handleImportSuccess" />
  </div>
</template>

<script setup lang="ts">
import { ProductStatus, FileType, type Brand, type Category, type ListProductFilters, type Product, type ExportProductFilters } from '@/interfaces/product.interface';
import { productService } from '@/services';
import { useFlashStore } from '@/stores/flash.store';
import { formatCurrency, formatProductStatusLabel, getProductStatusBadgeClasses } from '@/utils/formatter.util';
import { getProductImageUrl } from '@/utils/productImage.util';
import { computed, onMounted, reactive, ref } from 'vue';
import { useRouter } from 'vue-router';
import { toast } from 'vue3-toastify';
import ExportDropdown from '@/components/admin/ExportDropdown.vue';
import ImportProductModal from '@/components/admin/ImportProductModal.vue';

const router = useRouter();
const flashStore = useFlashStore();

const activeStates = reactive({
  active: true,
  inactive: true,
});
const brands = ref<Brand[]>([]);
const categories = ref<Category[]>([]);
const products = ref<Product[]>([]);
const isLoadingBrands = ref(false);
const isLoadingCategories = ref(false);
const isLoadingProducts = ref(false);
const isExporting = ref(false);
const isImporting = ref(false);
const metadata = reactive({
  currentPage: 1,
  pageSize: 20,
  totalPages: 1,
  totalRecords: 0,
});
const filters = reactive<ListProductFilters>({
  id: undefined,
  keyword: undefined,
  minPrice: undefined,
  maxPrice: undefined,
  status: '',
  availableFrom: undefined,
  isActive: undefined,
  brandId: '',
  categoryIds: [],
  page: 1,
  size: 20,
});

const productStatuses = computed(() => Object.values(ProductStatus));

const loadBrands = async () => {
  isLoadingBrands.value = true;
  try {
    const { data } = await productService.listBrand();
    brands.value = data;
  } catch (error) {
    toast.error('Failed to load brands');
  } finally {
    isLoadingBrands.value = false;
  }
};

const loadCategories = async () => {
  isLoadingCategories.value = true;
  try {
    const { data } = await productService.listCategory();
    categories.value = data;
  } catch (error) {
    toast.error('Failed to load categories');
  } finally {
    isLoadingCategories.value = false;
  }
};

const handleActiveStateChange = () => {
  if (activeStates.active && activeStates.inactive) {
    filters.isActive = undefined;
  } else if (activeStates.active) {
    filters.isActive = true;
  } else if (activeStates.inactive) {
    filters.isActive = false;
  } else {
    filters.isActive = undefined;
  }
};

const applyFilters = async (page: number) => {
  if (isLoadingProducts.value) return;

  isLoadingProducts.value = true;
  try {
    filters.page = page;
    metadata.currentPage = page;
    const response = await productService.listProduct(filters);
    products.value = response.data;
    Object.assign(metadata, response.metadata);
  } catch (error) {
    toast.error('Failed to load products');
  } finally {
    isLoadingProducts.value = false;
  }
};

const changePage = (newPage: number) => {
  if (newPage >= 1 && newPage <= metadata.totalPages) {
    applyFilters(newPage);
  }
};

const resetFilters = () => {
  activeStates.active = true;
  activeStates.inactive = true;
  Object.assign(filters, {
    id: undefined,
    keyword: undefined,
    minPrice: undefined,
    maxPrice: undefined,
    status: '',
    availableFrom: undefined,
    isActive: undefined,
    brandId: '',
    categoryIds: [],
    page: 1,
    size: 20,
  });
  applyFilters(1);
};

const handleDelete = async (productId: number) => {
  if (!confirm('Are you sure you want to delete this product?')) return;

  try {
    await productService.deleteProduct(productId);
    toast.success('Product deleted successfully');
    applyFilters(metadata.currentPage); // Preserve current page after deletion
  } catch (error) {
    toast.error('Failed to delete product');
  }
};

const handleExport = async (fileType: 'csv' | 'excel') => {
  if (isExporting.value) return;

  isExporting.value = true;
  try {    
    const exportFilters: ExportProductFilters = {
      id: filters.id,
      keyword: filters.keyword,
      minPrice: filters.minPrice,
      maxPrice: filters.maxPrice,
      status: filters.status,
      availableFrom: filters.availableFrom,
      isActive: filters.isActive,
      brandId: filters.brandId,
      categoryIds: filters.categoryIds,
      fileType: fileType === 'csv' ? FileType.CSV : FileType.EXCEL
    };
    await productService.exportProduct(exportFilters);
    toast.success(`Products exported successfully as ${fileType.toUpperCase()}`);
  } catch (error) {
    console.error('Export failed:', error);
    toast.error('Failed to export products');
  } finally {
    isExporting.value = false;
  }
};

const handleImportClick = () => {
  const modalElement = document.getElementById('importProductModal');
  if (modalElement) {
    modalElement.classList.add('show');
    modalElement.style.display = 'block';
    modalElement.setAttribute('aria-modal', 'true');
    modalElement.setAttribute('role', 'dialog');
    
    // Add backdrop
    const backdrop = document.createElement('div');
    backdrop.className = 'modal-backdrop fade show';
    backdrop.id = 'modal-backdrop';
    document.body.appendChild(backdrop);
    
    // Add body class
    document.body.classList.add('modal-open');
  }
};

const handleImportSuccess = () => {
  // Refresh the product list after successful import
  applyFilters(1);
};

onMounted(async () => {
  try {
    await Promise.all([
      loadBrands(),
      loadCategories(),
      applyFilters(1),
    ]);
    if (flashStore.successMessage) toast.success(flashStore.successMessage);
    if (flashStore.errorMessage) toast.error(flashStore.errorMessage);
  } finally {
    isLoadingProducts.value = false;  // Ensure it's set to false after initial load
  }
});
</script>

<style scoped>
.table-responsive {
  min-height: 200px;
}

/* Use Bootstrap's .table-hover instead of custom hover styles */

/* Use Bootstrap's .shadow-sm instead of custom image shadows */
</style>
