// frontend/admin/src/components/admin/UserList.tsx
"use client";

import { Metadata } from "@/api/apiClient";
import { iamAdminApi } from "@/api/index.api";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Pagination,
  PaginationContent,
  PaginationItem,
  PaginationLink,
  PaginationNext,
  PaginationPrevious,
} from "@/components/ui/pagination";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { ROLES } from "@/constants";
import type { ListUserFilters, User } from "@/interfaces/user.interface";
import { Loader2, RotateCcw, Search } from "lucide-react";
import React, { useCallback, useEffect, useRef, useState } from "react";
import { toast } from "sonner";

const UserList: React.FC = () => {
  const isInitialized = useRef(false);
  const [users, setUsers] = useState<User[]>([]);
  const [isLoadingUsers, setIsLoadingUsers] = useState(true);
  const [filters, setFilters] = useState<ListUserFilters>({
    id: undefined,
    keyword: undefined,
    role: undefined,
    page: 1,
    size: 20,
  });
  const [metadata, setMetadata] = useState<Metadata>({
    currentPage: 1,
    pageSize: 20,
    totalPages: 1,
    totalRecords: 0,
  });

  const applyFilters = useCallback(
    async (page: number, currentFilters?: ListUserFilters) => {
      setIsLoadingUsers(true);
      try {
        const filtersToUse = currentFilters || filters;
        const updatedFilters = { ...filtersToUse, page };
        setFilters(updatedFilters);
        setMetadata((prev) => ({ ...prev, currentPage: page }));

        // Clean up empty or undefined filters for API call
        const apiFilters: ListUserFilters = { ...updatedFilters };
        Object.keys(apiFilters).forEach((key) => {
          const typedKey = key as keyof ListUserFilters;
          if (
            apiFilters[typedKey] === "" ||
            apiFilters[typedKey] === undefined
          ) {
            delete apiFilters[typedKey];
          }
        });

        const response = await iamAdminApi.retrieveUserList(apiFilters);

        if (response.success) {
          setUsers(response.data || []);
          if (response.metadata) {
            setMetadata(response.metadata);
          }
        } else {
          toast.error(response.errorMessage || "Failed to load users");
        }
      } catch (error: unknown) {
        const errorMessage =
          error instanceof Error ? error.message : "Failed to load users";
        toast.error(errorMessage);
        setUsers([]);
      } finally {
        setIsLoadingUsers(false);
      }
    },
    [filters]
  );

  const changePage = useCallback(
    (newPage: number) => {
      if (newPage >= 1 && newPage <= metadata.totalPages) {
        applyFilters(newPage);
      }
    },
    [metadata.totalPages, applyFilters]
  );

  const resetFilters = useCallback(() => {
    const resetFiltersData: ListUserFilters = {
      id: undefined,
      keyword: undefined,
      role: undefined,
      page: 1,
      size: 20,
    };
    setFilters(resetFiltersData);
    applyFilters(1, resetFiltersData);
  }, [applyFilters]);

  const handleFilterChange = useCallback(
    (
      field: keyof ListUserFilters,
      value: string | number | boolean | undefined
    ) => {
      setFilters((prev) => ({ ...prev, [field]: value }));
    },
    []
  );

  const handleSearch = useCallback(() => {
    applyFilters(1);
  }, [applyFilters]);

  // Load initial data on component mount
  useEffect(() => {
    if (isInitialized.current) {
      return;
    }

    isInitialized.current = true;

    const initializeData = async () => {
      await applyFilters(1);
    };
    initializeData();
  }, [applyFilters]);

  return (
    <div className="space-y-6">
      <Card>
        <CardHeader>
          <CardTitle>User Filters</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
            <div className="space-y-2">
              <Label htmlFor="userId">User ID</Label>
              <Input
                type="number"
                id="userId"
                placeholder="Enter user ID"
                value={filters.id || ""}
                onChange={(e) =>
                  handleFilterChange(
                    "id",
                    e.target.value ? parseInt(e.target.value) : undefined
                  )
                }
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="keyword">Keyword</Label>
              <Input
                type="text"
                id="keyword"
                placeholder="Enter username, first name, last name, email, or phone number"
                value={filters.keyword || ""}
                onChange={(e) =>
                  handleFilterChange("keyword", e.target.value || undefined)
                }
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="role">Role</Label>
              <Select
                value={filters.role}
                onValueChange={(value) => handleFilterChange("role", value)}
              >
                <SelectTrigger>
                  <SelectValue placeholder="All Roles" />
                </SelectTrigger>
                <SelectContent>
                  {ROLES.map((role) => (
                    <SelectItem key={role} value={role}>
                      {role}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
          </div>
          <div className="flex justify-start space-x-2 mt-4">
            <Button onClick={handleSearch} disabled={isLoadingUsers}>
              <Search className="h-4 w-4 mr-2" />
              Search
            </Button>
            <Button
              variant="outline"
              onClick={resetFilters}
              disabled={isLoadingUsers}
            >
              <RotateCcw className="h-4 w-4 mr-2" />
              Reset
            </Button>
          </div>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>User Results</CardTitle>
        </CardHeader>
        <CardContent>
          {isLoadingUsers ? (
            <div className="flex flex-col items-center justify-center py-12">
              <Loader2 className="h-8 w-8 animate-spin text-primary" />
              <p className="mt-2 text-muted-foreground">Loading users...</p>
            </div>
          ) : (
            <div className="rounded-md border">
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>ID</TableHead>
                    <TableHead>Username</TableHead>
                    <TableHead>Name</TableHead>
                    <TableHead>Email</TableHead>
                    <TableHead>Phone</TableHead>
                    <TableHead>Role</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {users.length === 0 ? (
                    <TableRow>
                      <TableCell
                        colSpan={6}
                        className="text-center py-8 text-muted-foreground"
                      >
                        No users found
                      </TableCell>
                    </TableRow>
                  ) : (
                    users.map((user) => (
                      <TableRow key={user.id}>
                        <TableCell>{user.id}</TableCell>
                        <TableCell>{user.username}</TableCell>
                        <TableCell>
                          {user.firstName && user.lastName
                            ? `${user.firstName} ${user.lastName}`
                            : "N/A"}
                        </TableCell>
                        <TableCell>{user.email || "N/A"}</TableCell>
                        <TableCell>{user.phoneNumber || "N/A"}</TableCell>
                        <TableCell>
                          <Badge
                            variant={
                              user.role === "ADMIN" ? "default" : "secondary"
                            }
                          >
                            {user.role}
                          </Badge>
                        </TableCell>
                      </TableRow>
                    ))
                  )}
                </TableBody>
              </Table>
            </div>
          )}
        </CardContent>
      </Card>

      {/* Pagination */}
      {metadata.totalPages > 1 && (
        <div className="flex items-center justify-between">
          <div className="text-sm text-muted-foreground">
            Page {metadata.currentPage} of {metadata.totalPages} (
            {metadata.totalRecords} records)
          </div>
          <Pagination>
            <PaginationContent>
              <PaginationItem>
                <PaginationPrevious
                  href="#"
                  onClick={(e) => {
                    e.preventDefault();
                    if (metadata.currentPage > 1) {
                      changePage(metadata.currentPage - 1);
                    }
                  }}
                  className={
                    metadata.currentPage <= 1
                      ? "pointer-events-none opacity-50"
                      : ""
                  }
                />
              </PaginationItem>

              {/* Page numbers */}
              {Array.from(
                { length: Math.min(5, metadata.totalPages) },
                (_, i) => {
                  const pageNumber =
                    Math.max(
                      1,
                      Math.min(
                        metadata.totalPages - 4,
                        metadata.currentPage - 2
                      )
                    ) + i;

                  if (pageNumber <= metadata.totalPages) {
                    return (
                      <PaginationItem key={pageNumber}>
                        <PaginationLink
                          href="#"
                          onClick={(e) => {
                            e.preventDefault();
                            changePage(pageNumber);
                          }}
                          isActive={pageNumber === metadata.currentPage}
                        >
                          {pageNumber}
                        </PaginationLink>
                      </PaginationItem>
                    );
                  }
                  return null;
                }
              )}

              <PaginationItem>
                <PaginationNext
                  href="#"
                  onClick={(e) => {
                    e.preventDefault();
                    if (metadata.currentPage < metadata.totalPages) {
                      changePage(metadata.currentPage + 1);
                    }
                  }}
                  className={
                    metadata.currentPage >= metadata.totalPages
                      ? "pointer-events-none opacity-50"
                      : ""
                  }
                />
              </PaginationItem>
            </PaginationContent>
          </Pagination>
        </div>
      )}
    </div>
  );
};

export default UserList;

// frontend/src/pages/admin/UserList.vue
<template>
  <div class="container-fluid px-5 py-4">
    <div class="d-flex justify-content-between align-items-center mb-4">
      <div>
        <h3 class="mb-1">User Management</h3>
        <p class="text-muted mb-0">Manage your user accounts</p>
      </div>
    </div>

    <!-- Filters Card -->
    <div class="card mb-4 shadow-sm">
      <div class="card-header bg-light py-3">
        <h5 class="mb-0">Search Filters</h5>
      </div>
      <div class="card-body p-4">
        <form @submit.prevent="applyFilters(1)">
          <div class="row g-4">
            <div class="col-md-6">
              <label for="userId" class="form-label">User ID</label>
              <input
                id="userId"
                v-model.trim="filters.id"
                type="text"
                class="form-control"
                placeholder="Enter user ID"
              />
            </div>
            <div class="col-md-6">
              <label for="keyword" class="form-label">Search</label>
              <input
                id="keyword"
                v-model.trim="filters.keyword"
                type="text"
                class="form-control"
                placeholder="Search by username, name, or email"
              />
            </div>
            <div class="col-md-6">
              <label for="role" class="form-label">Role</label>
              <select
                id="role"
                v-model="filters.role"
                class="form-select"
              >
                <option value="">All Roles</option>
                <option value="ADMIN">Admin</option>
                <option value="USER">User</option>
              </select>
            </div>
          </div>
          <div class="d-flex gap-2 mt-4 pt-3 border-top">
            <button type="submit" class="btn btn-primary">
              <i class="bi bi-search"></i> Search
            </button>
            <button type="button" @click="resetFilters" class="btn btn-outline-secondary">
              <i class="bi bi-arrow-counterclockwise"></i> Reset
            </button>
          </div>
        </form>
      </div>
    </div>

    <!-- Users Table -->
    <div class="card shadow-sm">
      <div class="card-header bg-light py-3">
        <h5 class="mb-0">User List</h5>
      </div>
      <div v-if="isLoadingUsers" class="text-center py-5" aria-live="polite">
        <div class="spinner-border text-primary" role="status" aria-label="Loading users">
          <span class="visually-hidden">Loading...</span>
        </div>
      </div>
      <div v-else class="card-body p-0">
        <div class="table-responsive">
          <table class="table table-hover table-bordered mb-0">
            <thead class="table-light">
              <tr>
                <th scope="col" class="px-4">ID</th>
                <th scope="col" class="px-4">Username</th>
                <th scope="col" class="px-4">Name</th>
                <th scope="col" class="px-4">Email</th>
                <th scope="col" class="px-4">Phone</th>
                <th scope="col" class="px-4">Role</th>
              </tr>
            </thead>
            <tbody>
              <tr v-for="user in users" :key="user.id">
                <td class="px-4">{{ user.id }}</td>
                <td class="px-4">{{ user.username }}</td>
                <td class="px-4">{{ user.firstName }} {{ user.lastName }}</td>
                <td class="px-4">{{ user.email }}</td>
                <td class="px-4">{{ user.phoneNumber || 'N/A' }}</td>
                <td class="px-4">
                  <span :class="getRoleBadgeClasses(user.role as Role)">
                    {{ user.role }}
                  </span>
                </td>
              </tr>
              <tr v-if="!users.length">
                <td colspan="6" class="text-center text-muted py-4">
                  No users found
                </td>
              </tr>
            </tbody>
          </table>
        </div>

        <!-- Pagination -->
        <div class="card-footer bg-light py-3">
          <div class="d-flex justify-content-between align-items-center">
            <span class="text-muted">
              Page {{ metadata.currentPage }} of {{ metadata.totalPages }}
              <span class="ms-2">({{ metadata.totalRecords }} records)</span>
            </span>
            <div class="btn-group">
              <button
                @click="changePage(metadata.currentPage - 1)"
                :disabled="metadata.currentPage <= 1"
                class="btn btn-outline-secondary px-3"
              >
                Previous
              </button>
              <button
                @click="changePage(metadata.currentPage + 1)"
                :disabled="metadata.currentPage >= metadata.totalPages"
                class="btn btn-outline-secondary px-3"
              >
                Next
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import type { Role } from '@/constants/app.constants';
import type { ListUserFilters, User } from '@/interfaces/user.interface';
import { userService } from '@/services';
import { getRoleBadgeClasses } from '@/utils/formatter.util';
import { onMounted, reactive, ref } from 'vue';
import { toast } from 'vue3-toastify';

const users = ref<User[]>([]);
const isLoadingUsers = ref(true);
const metadata = reactive({
  currentPage: 1,
  pageSize: 20,
  totalPages: 1,
  totalRecords: 0,
});
const filters = reactive<ListUserFilters>({
  id: undefined,
  keyword: undefined,
  role: '',
  page: 1,
  size: 20,
});

const applyFilters = async (page: number) => {
  isLoadingUsers.value = true;
  try {
    filters.page = page;
    metadata.currentPage = page;

    // Clean up empty or undefined filters
    const apiFilters: ListUserFilters = { ...filters };
    Object.keys(apiFilters).forEach((key) => {
      const typedKey = key as keyof ListUserFilters;
      if (apiFilters[typedKey] === '' || apiFilters[typedKey] === undefined) {
        delete apiFilters[typedKey];
      }
    });

    console.log('Fetching users with filters:', apiFilters);
    const response = await userService.listUser(apiFilters);
    
    if (response.success) {
      users.value = response.data || [];
      if (response.metadata) {
        Object.assign(metadata, response.metadata);
      }
      console.log('Users loaded:', users.value.length);
    } else {
      toast.error(response.errorMessage || 'Failed to load users');
      console.error('Failed to load users:', response.errorMessage);
    }
  } catch (error: any) {
    console.error('Error loading users:', error);
    toast.error(error.message || 'Failed to load users');
    // Initialize empty array to avoid undefined errors
    users.value = [];
  } finally {
    isLoadingUsers.value = false;
  }
};

const changePage = (newPage: number) => {
  if (newPage >= 1 && newPage <= metadata.totalPages) {
    applyFilters(newPage);
  }
};

const resetFilters = () => {
  Object.assign(filters, {
    id: undefined,
    keyword: undefined,
    role: undefined,
    page: 1,
    size: 20,
  });
  applyFilters(1);
};

// Always fetch users when component mounts
onMounted(() => {
  console.log('UserList component mounted, fetching users...');
  applyFilters(1);
});
</script>

<style scoped>
.table-responsive {
  min-height: 200px;
}
</style>
